### PR TITLE
feat(backend): lock failed login attempts

### PR DESCRIPTION
**Pull request by pbn4**
# Pull Request Template

## Issue Overview

This PR addresses #1927 

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This change adds locking / cooldown period for account login after a configurable number of failed login attempts. 

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Go to login page and try logging in 5 times in a row with wrong password, next attempt will return http status code 429 instead of 400, and the backend response will contain retryAfter timestamp in body, informing when next login attempt is allowed. 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by emilyjablonski** [comment]
Backend LGTM, is someone assigned to pick up the frontend yet? Can bring up in standup tmrw

**Comment by pbn4** [comment]
@emilyjablonski I don't think so, also it can probably be part of a separate PR. What do you think?

**Comment by emilyjablonski** [comment]
@pbn4 Lemme ping Kathy, it's technically in this issue

**Comment by dominikx96** [comment]
@pbn4 I'll create separate PR to cover frontend part

**Comment by seanmalbert** [comment]
Added `on hold` label until the front-end (#2260) piece is merged into this.

**Comment by emilyjablonski** [comment]
I can't get the Figma links to work but this messaging seems off to me. I try to log-in with a failed password and every failed attempt has this message:
Screen Shot 2021-12-07 at 11 31 19 AM

So even after 4 failed attempts it will say "5 more attempts" which to me makes it seem like I have 5 left. I feel like it should read "after 5 failed attempts" - will ping Kathy.

**Comment by kathyccheng** [comment]
@emilyjablonski Yep agreed "after 5 failed attempts"

**Review by seanmalbert — CHANGES_REQUESTED** [review]
@pbn4 and @dominikx96 , please see @emilyjablonski comment on the messaging.

**Comment by dominikx96** [comment]
@emilyjablonski I updated translations (also replaced two hardcoded by translated strings) and resolved conflicts.

**Review by seanmalbert — APPROVED** [review]

**Pull request merged**
