### PR TITLE
chore: move Programs step to come after Students

### PR DESCRIPTION
**Pull request by jaredcwhite**
# Pull Request Template

## Issue Overview

This PR addresses #2221 

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

The programs step in the application submission process had been placed directly after ADA options. Now it's placed after household changes and students.

## How Can This Be Tested/Reviewed?

Apply to a listing using the online forms and make sure the programs show up right before the income verification step.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by emilyjablonski — CHANGES_REQUESTED** [review]
This didn't fail our app submission Cypress test and it should have because there are no changes to the step order in applicationData.tsx - can you update the test to follow this new flow?

**Comment by jaredcwhite** [comment]
@emilyjablonski Yeah, I assumed I'd need to update Cypress tests but I was having problems getting it to run on my machine recently. Kept acting like localhost:3000 wasn't responding even though it was. I'll have to slog through updating the branch here to test in CircleCI…

**Comment by emilyjablonski** [comment]
@jaredcwhite You should be able to test locally, and I bet that would be easier to finagle than CircleCI - let me know if you want to pair

**Comment by jaredcwhite** [comment]
Sigh…so close. I've gotten the latest dev fixes for Cypress merged in and my changes to the test should be working, but I've run into a discrepancy between how Cypress is working in CircleCI and locally.

I had to add this line to get tests working locally: https://github.com/bloom-housing/bloom/blob/e153657b75e3cf08c8b64e652a359503efac60c3/sites/public/cypress/support/commands.js#L50

Yet that's _not_ working in CircleCI. 😟 And if you think about it logically, that line really should be there, because you can't go ahead and fill out First Name, Last Name, etc. if you've chosen to autofill the application using saved data.

**Comment by jaredcwhite** [comment]
OK figured out the Cypress tests issue for the time being. Made sure we got expected failures due to the changed form steps and then fixed those.

**Review by emilyjablonski — APPROVED** [review]
lgtm!

**Pull request merged**
