### PR TITLE
refactor: flatten translations strings, separate partners strings

### PR DESCRIPTION
**Pull request by emilyjablonski**
# Pull Request Template

## Issue Overview

This PR addresses #2514

- [x] This change addresses only certain aspects of the issue

Remaining work: jurisdiction uptake, removing all plaintext strings from partners

## Description

* Flattened all of our translations files from their object format for usability - added a script to do this so we can use it in jurisdictions
* Separated out strings that are only used in partners to the partners english strings override file (did this manually 😭)
* Removed unused keys that do not have translations, kept in unused keys that do have translations
* Removed duplicate translations where possible (some are duplicated across preferences, where we are dynamically getting the key based on the preference prefix, so removing these duplicates would be a bigger change) - added a script to find duplicate values
* Updated the missing translations script to account for the new flattened format (here are the [missing public strings](https://docs.google.com/spreadsheets/d/1B063YeMOt2vakl1uZxsLvbAI8EwfbdV8B_z_uNKtiJw/edit#gid=0) off of this PR)
* Removed a few plaintext strings from partners, but my recommendation is to do this as we go from now on as we see them
* Added a script to check if there are keys in foreign translation files that do not exist in the english file

Uptaking this in jurisdictions might be a little tricky since there are some jurisdictionally specific strings that may have been added to the general file. My recommendation would be to run the flatten script over there, pull out the same strings to the partners file based on our core partners overrides, and check for differences to see if there are any strings added to the english file. Could be a little tedious, but we shouldn't just keep the same core files without checking.

## How Can This Be Tested/Reviewed?

I think this might be pretty challenging to review. Since pulling out the partners strings required lots of manual checking, it's possible I moved a string into the partners overrides file that is still used in public. I did run through all the strings twice, but that seems challenging to test. You could review the flatten script and ensure it's pulling all the strings through.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by YazeedLoonat — CHANGES_REQUESTED** [review]
Hey @emilyjablonski I really like these changes
only thing I found on an application's detail page on the partner's side we have a few "missing translations" pop up in the console

**Comment by emilyjablonski** [comment]
@YazeedLoonat That's an existing issue not to do with translations where the minimal table accepts translations keys and not pre-translated values - I think we're actually doing that in a lot of places, so I would love to handle that in a separate ticket, but let me know what you think!

**Review by YazeedLoonat — APPROVED** [review]
LGTM,
@emilyjablonski yeah I think we should spin up that separate ticket for it as that seems like we want to be able to test that separately

**Review by seanmalbert — APPROVED** [review]
@emilyjablonski ,

LGTM, I wasn't sure if it makes sense to keep `reformat-strings` now, so you may want to remove that.

**Comment by emilyjablonski** [comment]
@seanmalbert I think we will want it for when we uptake into jurisdictions, since we will need to do some massaging of the general files there as well for strings we added just in that jurisdiction

**Pull request merged**
