### PR TITLE
feat(backend): add bull job scheduler for afs processing

### PR DESCRIPTION
**Pull request by pbn4**
# Pull Request Template

## Issue Overview

This PR addresses #2835 

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This changes moves duplicates into an async worker. The worker is a part of the same process as backend service and uses Redis + Bull.js to schedule jobs to the queue. It uses repeatable jobs and according to docs Bull.js is smart enough to not post the same repeatable job twice into the queue, so there should be no duplicate / overlapping runs.

Processing logic (cc: @kathyccheng):
- processing runs once a day on midnight (cron string `0 0 * * *`) unless configured otherwise with env variable `AFS_PROCESSING_CRON_STRING`
- processing runs for all listings with status active
- on each processing run any existing AFS for a given Listing are removed and recreated
- processing is done in the background of web server process
- processing is also triggered by chaning Listing status from active to any (to cover the case where processing has already run, new applications were added after that and some of them are not included in AFS because processing will not run for closed Listings)

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by seanmalbert — CHANGES_REQUESTED** [review]
@pbn4 ,

I was thinking that we could cut down the processing further by only running `updateApplicationFlaggedSetsForRule` on applications that have not been processed. We can achieve this by fetching applications that were submitted since the last time the job ran or based off of a flag on the application. In either case, we wouldn't want to remove the flagged sets and only add to them.

We also want to be able to display the last time a job was ran. It's possible we could calculate that based off of the cron string or we could create a new job table to store that.

I thought we could also stop running the jobs once a listing was no longer open, but I discussed this with @kathyccheng earlier today and it's possible that a partner portal user could add applications via the portal after a listing has closed and we would want to flag duplicates if this were the case. If we update the job to only run on newly submitted applications this shouldn't be an issue. We could also consider not running the job on closed listings and always run it on paper applications submitted through the partner portal, if you saw any issues checking all active or closed listings for new applications each job.

**Comment by pbn4** [comment]
> We also want to be able to display the last time a job was ran. It's possible we could calculate that based off of the cron string or we could create a new job table to store that.

Sure what do you think about adding it as a column to the listing table? 

>I thought we could also stop running the jobs once a listing was no longer open, but I discussed this with @kathyccheng earlier today and it's possible that a partner portal user could add applications via the portal after a listing has closed and we would want to flag duplicates if this were the case. If we update the job to only run on newly submitted applications this shouldn't be an issue. We could also consider not running the job on closed listings and always run it on paper applications submitted through the partner portal, if you saw any issues checking all active or closed listings for new applications each job.

Currently job only fetches listings with state equal to active. So to summarize we want the job to run for every listing for every application that was submitted after the job was last run?

What if partner portal user updates the application in a way that triggers/cancels AFS rule? The fact that I'm running everything from scratch as long as listing is active handles this case, but handling per not processed basis makes it much more difficult because the AFS sets already exists and a change to application requires modifying existing sets to create/reverse rules triggered by application updates.

I assumed creating everything from scratch for active listings is an acceptable solutions because we were at some point aligned on the fact that frontend will not display AFS views as long as listing applications are not finished. I understand that now there is a case that someone can add an application to a Listing with status closed, right? 

We could still have it working in a batch by:
- by triggering reprocessing in such case (but that adds unnecessary f if/else logic, complicating the app submission code), 
- or having a boolean flag that controls reprocessing of AFS 
- or giving that control to the user in a form of a button

I'm trying to keep the batch processing of everything from scratch even if it's a bit not optimal because of the simplicity of the code.

**Comment by seanmalbert** [comment]
> Sure what do you think about adding it as a column to the listing table?

That sounds good to me.

> Currently job only fetches listings with state equal to active. So to summarize we want the job to run for every listing for every application that was submitted after the job was last run?
[...]
I'm trying to keep the batch processing of everything from scratch even if it's a bit not optimal because of the simplicity of the code.

I see your point about applications getting updated and keeping the process as simple as possible. I think having a boolean flag that we can use to determine if a closed listing has had an updated application could solve the problem of running it on closed listings, without having to do all listings each time. What do you think?

**Review by seanmalbert — APPROVED** [review]
@pbn4 ,
This looks good. I started with some performance updates in how we select listings and was going to continue, but since that afs work was brought over/existing, we can do the rest of that in a follow-up issue. That'll make it easier to track the changes too.

**Pull request merged**
