### PR TITLE
Translation nav

### PR DESCRIPTION
**Pull request by slowbot**
Adding placeholder component for translation navigation

### CODE REVIEW

**Comment by jaredcwhite** [comment]
@slowbot Think I got it working…weird thing is I don't know why it's working! Just seemed to resolve itself after Prettier autoformated a few lines.

JSX can be very odd sometimes…

**Comment by jaredcwhite** [comment]
@bk3c I think this will need to be rebased on master and conflicts resolved before I can review it effectively. I'm not sure what's new and what's old.

**Comment by bk3c** [comment]
@software-project do you think you could help out with the rebase and conflict sorting here?

**Comment by software-project** [comment]
@bk3c will have a look there now.

**Comment by jaredcwhite** [comment]
https://5ed66f9664600d2a20d3ec6d--clever-edison-cd22c1.netlify.app/

**Pull request merged**
