### PR TITLE
fix: if programs is null no longer errors

### PR DESCRIPTION
**Pull request by YazeedLoonat**
This PR addresses #4357 

- [x] Addresses the issue in full

## Description
When an application's program data was null, it would cause the a crash in the api when trying to do an export. This fixes that

## How Can This Be Tested/Reviewed?
- create an application that has `null` from program data
- attempt to export the application data for the listing the application was added to
- the app should no longer error and should return an export

## Author Checklist:

- [ ] Added QA notes to the issue with applicable URLs
- [x] Reviewed in a desktop view
- [ ] Reviewed in a mobile view
- [ ] Reviewed considering accessibility
- [ ] Added tests covering the changes
- [ ] Made corresponding changes to the documentation
- [ ] Ran `yarn generate:client` and/or created a migration when required

## Review Process:

- Read and understand the issue
- Ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review after the updates

### CODE REVIEW

**Comment by emilyjablonski** [comment]
How are you creating an application with null program data? Are you submitting an application to a listing without programs? Or not claiming any?

**Comment by YazeedLoonat** [comment]
@emilyjablonski thats a good question, the error comes from the `program` column being `null` on the application table's application record

I forced the error to happen by creating an application then setting the program value to null in the db via the db

**Comment by emilyjablonski** [comment]
@YazeedLoonat Do we know how this might have happening in staging?

**Comment by YazeedLoonat** [comment]
@emilyjablonski not really sure on how it happened. Both the API and the db support null programs and when digging into the export code I found that the spreadsheet export already had corrected for this

so my assumption was that there is a way to get this data into the db from the front end I just carried over the fix from the spreadsheet export to the csv export

**Comment by emilyjablonski** [comment]
Okay that all makes sense! Is there an easy way to add a test for this?

**Review by ColinBuyck — APPROVED** [review]
Vroom vroom 🛵

**Pull request merged**
