### PR TITLE
2501/resend invite

### PR DESCRIPTION
**Pull request by dominikx96**
# Pull Request Template

## Issue Overview

This PR addresses #2501

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Adds a new modal that is triggered when a user tries to log in, but an account is not confirmed. It gives the ability to resend a confirmation email. Also, reduced duplicated code.

## How Can This Be Tested/Reviewed?

1. Open partners login page
2. Reseed database
3. Try to log in using not confirmed user credentials (from seeds): `user+notconfirmed@example.com` / `abcdef`
4. You should see a confirmation modal with pre-filled email input
5. Try to resend an email and check the network tab -> you should see 200 status code
6. Try to provide an incorrect email -> you should see an error alert

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [x] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by emilyjablonski — CHANGES_REQUESTED** [review]
Visually this looks great! The resend email I receive though looks to still be the public resend email, so we'll need to make sure we are using the partners resend endpoint for the email.

**Comment by dominikx96** [comment]
@YazeedLoonat thanks! It works as expected to me :) @emilyjablonski could you review this PR again?

**Comment by emilyjablonski** [comment]
Screen Shot 2022-03-21 at 12 47 15 PM

**Comment by YazeedLoonat** [comment]
Hey @emilyjablonski I'm trying to replicate the issue you saw, but I'm not able to replicate

**Comment by emilyjablonski** [comment]
@YazeedLoonat I can repeat it again with the steps above, let me know if you want to pair!

**Comment by YazeedLoonat** [comment]
Hey @emilyjablonski so, from stand up it sounds like we are okay on punting on the multiple jurisdiction issue, lemme know if its okay to move this ahead even with this issue

**Review by emilyjablonski — APPROVED** [review]

**Review by seanmalbert — APPROVED** [review]

**Pull request merged**
