### PR TITLE
fix: re-enable CSS purging to minimize Tailwind bundles

### PR DESCRIPTION
**Pull request by jaredcwhite**
## Issue Overview

This PR addresses #3659 

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Due to an object spread, the ui-components Tailwind config which had `purge` `enabled` set to `false` was overwriting the two config files in the Next.js apps. This fixes those configs so that purges can happen in production for vastly smaller CSS bundle sizes.

## How Can This Be Tested/Reviewed?

Verify the size of the primary CSS bundle, and verify the purge didn't cause any obvious styling bugs (admittedly hard to tell with 100% coverage of the applications).

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [x] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by jaredcwhite** [comment]
Looking good on the public preview!
image

**Comment by jaredcwhite** [comment]
Partner's bundle is slightly larger, but still pretty reasonable imo (and certainly compared to before):
image

**Comment by ludtkemorgan** [comment]
@jaredcwhite I'm curious what tool you are using to get those numbers. I am using the built in bundle analyzer and the numbers I'm seeing are bigger than what you posted

**Comment by jaredcwhite** [comment]
@ludtkemorgan I'm using Safari and looking at the size of the primary CSS file which gets loaded. I'd assume Firefox or Chrome in their network tabs would report similar stats?

**Review by ludtkemorgan — APPROVED** [review]

**Pull request merged**
