### PR TITLE
feat: 3909/add redirect url prisma

### PR DESCRIPTION
**Pull request by cade-exygy**
# Pull Request Template

## Issue Overview
This PR implements the Mandated Accounts changes so it is compatible with Prisma

This PR addresses #3909

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description
- Added previous backend changes for Mandated Accounts to the Prisma email service and user service
- Handle undefined urls
- Add tests 

## How Can This Be Tested/Reviewed?

Ensure you are running on the Prisma version of Bloom Core
Perform Create Account and Forgot Password flow and ensure everything works properly
With MandatedAccounts feature flag enabled: When logged out, go to a listing and hit apply online
- Forget Password flow
- Create Account flow

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by YazeedLoonat — APPROVED** [review]
LGTM

**Comment by ColinBuyck** [comment]
Is this supposed to show the whole url instead of just the base url of the website?
Screenshot 2024-03-12 at 10 36 13 AM

**Comment by cade-exygy** [comment]
> Is this supposed to show the whole url instead of just the base url of the website? Screenshot 2024-03-12 at 10 36 13 AM

Yeah that is a good question. @slowbot, what are your thoughts on this? I didn't change the value the email is displaying here, which is the appUrl. Since we use the appUrl to generate the resetUrl, then those params are placed here. I suppose we could just pass the domain to the template?

**Comment by emilyjablonski** [comment]
Reminder that the PR title needs to be formatted like the commit messages

**Review by ColinBuyck — APPROVED** [review]
LGTM 🌽 Once those merge conflicts are resolved!

**Pull request merged**
