### PR TITLE
fix: app due date and time fixes

### PR DESCRIPTION
**Pull request by seanmalbert**
- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

I noticed this morning that our application due date checks do not take the due time into account. This fixes that. I originally opened this off of master, so had to rebase off of dev. As a result, for some reason files like the listing e2e tests are showing changes, but they're already on there.

## How Can This Be Tested/Reviewed?

Create or update a listing with a due date and time and you should see the due date checks using the time. The listing on public should correctly reflect the status based off of the due time.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by emilyjablonski — APPROVED** [review]

**Review by emilyjablonski — CHANGES_REQUESTED** [review]
Screen Shot 2021-11-01 at 11 57 05 AM

Sorry didn't meant to hit approve - if I create a listing where the due date is today at a later time it says it's closed

**Comment by seanmalbert** [comment]
@emilyjablonski ,
Thank you for the review, I fixed the issue you called out. Can you please re-review?

**Comment by emilyjablonski** [comment]
If I make a listing with just an application due date that is today and no time, it shows as closed. That seems incorrect to me but I'm not sure? I feel like the default time should be midnight if not provided maybe?

**Comment by seanmalbert** [comment]
@emilyjablonski ,

> If I make a listing with just an application due date that is today and no time, it shows as closed. That seems incorrect to me but I'm not sure? I feel like the default time should be midnight if not provided maybe?
> 

I think you're right, and that it should default to 23:59:59 of that day, if not time. Alternatively, we could also require time to be set. @kathyccheng , can we require the application due time?

> Additionally if I update a listing so that it is closed and then change the due date to today, but later, it still shows as closed.

It does this if I click `save & exit`, which I think is expected. However, if I click publish, I see it get set to open.

**Comment by kathyccheng** [comment]
@seanmalbert @emilyjablonski I'm okay with requiring time if it's a part of the overall date / time? like if they enter a date, it's not valid without a time. but not requiring the time field on its own.

**Comment by emilyjablonski** [comment]
@seanmalbert Looks like we want to require the time field if we have the due date field. Let me know if you want me to pick this one up.

**Comment by seanmalbert** [comment]
closing

**Pull request closed without merging**
