### PR TITLE
fix: public site user confirmation issue (#561)

### PR DESCRIPTION
**Pull request by YazeedLoonat**
This is a cherry pick for https://github.com/housingbayarea/bloom/pull/561

**testing:**
head over to the public site ( https://hba-public-main.netlify.app/)
attempt to create a new account
get the email
click the confirmation link
you should now be signed in

### CODE REVIEW

**Review by ColinBuyck — COMMENTED** [review]
I'm unfortunately still seeing the issue on the hba dev site. Let me know if I'm missing anything!

https://user-images.githubusercontent.com/53269332/208196783-08182b59-20e3-4688-899a-9d76c4b680e6.mov

**Comment by YazeedLoonat** [comment]
Hey @ColinBuyck if you wanna repeep, we hadn't changed hba-public to deploy with the main branch that should be fixed now if you wanna take another look 

url has been updated per changes from morgan

**Review by ludtkemorgan — APPROVED** [review]
It worked for me locally!

**Review by ColinBuyck — APPROVED** [review]
All good now 🌵 thanks!

**Pull request merged**
