### PR TITLE
fix: add backend url validation for url fields

### PR DESCRIPTION
**Pull request by KrissDrawing**
# Pull Request Template

## Issue Overview

This PR addresses #3510

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Adds backend validation for url fields. It should make a difference only for digital application url, as rest has it's own frontend validation, so technically we can't push invalid url field.
Also for it to work i had to fix an issue with application types section reseting on submit (when error). So on edit it took value from listing, even though form value was different.
Also fixed an issue where we could have no digital application selected, but field for url was visible.

## How Can This Be Tested/Reviewed?

On partners site go to edit listing. In application process select `yes` in `is there digital application`, in url field provide invalid url. After submit it should highlight error and display error message. 
I suspect that mocked listings might have mutually exclusive values, so like digitalApplication might have application of "internal" type, but field for `commonDigitalApplication: false` which should result in `externalLink` type (cause thats only case it's not working for me, if i change it and save then it works fine).
Also now after selecting `is there a digital application` -> yes, then `Are you using the common digital application?` -> no, then `is there a digital application` -> no, it should not display url field (i believe that change shouldn't broke apps without common digital application, but worth to double check)

Check other fields if they work fine (to check if backend works i commented out "type="url" prop from fields):
- Open house event
- Building selection criteria
- Settings - preference url
- Settings - preference option url

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by ColinBuyck** [comment]
Just a heads up that there seems to be some testing issues to resolve here 🌵

**Comment by KrissDrawing** [comment]
i fixed the test issues, but i believe there is something wrong with whole application type section. Cause it may pass wrong application type, so it won't trigger validation, even though visually it has proper fields selected.

**Review by ColinBuyck — COMMENTED** [review]
I don't think I'm fully following the PR test description but I got the behavior below for an invalid url and when editing a new listing (not one from seeded data), I get the same thing. Is this expected?

https://github.com/bloom-housing/bloom/assets/53269332/71d10f32-38e7-476e-be05-49cb03f1d7e7

**Comment by KrissDrawing** [comment]
Right, good catch, i thought it's impossible to recreate 😅. So listings might have `commonDigitalApplicationChoice` as `false` (no) even when no digital application, and after switching to digital application default method is set to Internal (in this case we got `Internal` method but `commonDigitalApplicationChoice` was false, so we could type link). So to fix that i used application method type as indicator which default value chose.

**Review by emilyjablonski — APPROVED** [review]
Screenshot 2023-08-11 at 8 29 58 AM
Screenshot 2023-08-11 at 8 29 52 AM

This LGTM, my only comment is that we should standardize the error message across all the fields
We only have the "valid URL" version on the custom digital application field

**Comment by ColinBuyck** [comment]
@emilyjablonski Curious of your thoughts on this since I also found this error experience on the preference option url flow where both errors are used depending on the issue with the URL. 

https://github.com/bloom-housing/bloom/assets/53269332/03f909a7-7fd3-41ab-a33c-1d52c0cddfae

**Comment by KrissDrawing** [comment]
I can try some custom validators instead of `IsUrl`, that will return different backend errors for different case (without https, and for invalid url, but with https). So it will work similar to frontend validation. If that will take too much effort or sth i'll let you know

**Review by emilyjablonski — APPROVED** [review]
This looks great! Loving the consistency of the experience

**Comment by ludtkemorgan** [comment]
@ColinBuyck can you take another look at this PR?

**Review by ColinBuyck — APPROVED** [review]
So good! Thanks for making these updates 🐧

**Pull request merged**
