### PR TITLE
Migrate unit summary amiPercentage to int

### PR DESCRIPTION
**Pull request by avaleske**
# Pull Request Template

## Issue
Migrate unit summary AMI Percentage field to integer, to support filtering

Addresses CityOfDetroit/bloom#478

- [x] This change addresses only certain aspects of the issue

## Description
Migrate the amiPercentage column on the unit summary table to an integer, so we can filter based on it.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Can This Be Tested/Reviewed?

- [x] Try running the migration, and make sure the site still starts. The field is unused so far, so there should be no data issues.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [x] I have updated the changelog to include a description of my changes

### CODE REVIEW

**Comment by avaleske** [comment]
@seanmalbert and @willrlin for visibility

**Comment by avaleske** [comment]
Also looks like linters are still failing on forks.

**Comment by avaleske** [comment]
And the failing test is a rate-limiting issue.

**Comment by seanmalbert** [comment]
@pbn4 , can you please review.

**Review by seanmalbert — APPROVED** [review]
Thank you, @avaleske, looks good!

**Pull request merged**
