### PR TITLE
fix: update dependencies for backend

### PR DESCRIPTION
**Pull request by ludtkemorgan**
# Pull Request Template

Updates some out of date dependencies that may or may not have security flags against them

## Description

These are all dependencies that synk has attempted to upgrade for Doorway. This PR just manually does it in core so that it is kept in sync with Doorway

## How Can This Be Tested/Reviewed?

**PG and axios**: Minor versions - Tested by making sure the app runs and API calls are made
google translate: Major version - test that changing to a different language on the listings page still works
swagger-ui: minor version - `/docs` page should still work
new-relic: we don't actively use this but don't want to delete the code in the codebase

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by emilyjablonski** [comment]
@ludtkemorgan Do you mind commenting or filling out the PR template with anything you think needs to be tested in particular?

**Comment by ColinBuyck** [comment]
@ludtkemorgan Just a quick bump on Emily's comment above!

**Comment by ludtkemorgan** [comment]
@ColinBuyck @emilyjablonski I have updated the testing portion to highlight what these changes impact

**Comment by emilyjablonski** [comment]
@ludtkemorgan Just a heads up on some failing tests

**Pull request merged**
