### PR TITLE
fix: lottery confirmation in email translations

### PR DESCRIPTION
**Pull request by jaredcwhite**
## Issue Overview

This PR addresses #2330

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This is a fix—the email confirmation should only have two states, whether a listing is lottery order or FCFS. The previous three states logic was incorrect.

## How Can This Be Tested/Reviewed?

I believe @seanmalbert needs to merge this into dev, like before?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [x] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by emilyjablonski — CHANGES_REQUESTED** [review]
@jaredcwhite I double checked w Kathy on the strings in the ticket just to be sure, and then the backend test is related, should be an easy fix

**Comment by jaredcwhite** [comment]
@kathyccheng @emilyjablonski So…this brings us back around to an issue with the translations then, because we never got translations for the lottery language, only the waitlist language. For example in Spanish we have the FCFS text which is fine but the other text is: "Los solicitantes serán contactados por el agente en orden de lista de espera hasta que se cubran las vacantes." which according to Google Translate is: "Applicants will be contacted by the agent in waitlist order until vacancies are filled."

We'd need https://docs.google.com/document/d/1oh3kIYrp7K-n2MvPL8R3qqoZJaiwDVNk6EIbdNlj-ro/edit and the other two locales to get updated with translations for the lottery text: "Applicants will be contacted by the agent in lottery rank order until vacancies are filled."

**Comment by emilyjablonski** [comment]
Ahh yeah we are missing those - we could potentially in the short term make them all the english string but will leave it up to Kathy

**Comment by ludtkemorgan** [comment]
@jaredcwhite I'm guessing this PR can be closed? But want to get your confirmation before I close it

**Pull request closed without merging**
