### PR TITLE
2730/new partner email

### PR DESCRIPTION
**Pull request by dominikx96**
# Pull Request Template

## Issue Overview

This PR addresses #2730

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Creates email invite template that is used for inviting partner users, figma: https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-public-general?node-id=1943%3A8152

## How Can This Be Tested/Reviewed?

1. Open partners /users
2. Try to invite a user
3. Check your inbox and compare email with designs

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [x] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [x] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by dominikx96** [comment]
@jaredcwhite I'm not sure about footer translations. I just used the default layout so I assume it will be implemented separately for all jurisdictions/in your PR?

**Review by emilyjablonski — CHANGES_REQUESTED** [review]
Screen Shot 2022-06-13 at 3 19 55 PM

**Review by emilyjablonski — CHANGES_REQUESTED** [review]
Image and footer looks great!
Super sorry for the review cycle on this I just missed this before, but there are two strings that need updates:
`You will now be able to manage listings and applications that you are a part of from one centralized location test.` --> `You will now be able to manage listings and applications that you are a part of from one centralized location.`
And `Welcome to the Partners Portal on` --> `Welcome to the Partners Portal at`

**Comment by emilyjablonski** [comment]
@slowbot Unfortunately not because it includes backend changes

**Comment by dominikx96** [comment]
@emilyjablonski I've updated translations :)

**Review by emilyjablonski — APPROVED** [review]

**Pull request merged**
