### PR TITLE
1988/adds listing management cypress tests to partner portal

### PR DESCRIPTION
**Pull request by YazeedLoonat**
## Issue Overview

This PR addresses #issue
https://github.com/bloom-housing/bloom/issues/1988

- [x] This change addresses the issue in full

## Description
Adds cypress testing to the partner's portal for listing management

## How Can This Be Tested/Reviewed?
Check out the tests and run them on the partner's side

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by YazeedLoonat** [comment]
Hey @emilyjablonski  I made a lot of the changes you asked for here, the only thing I didn't address was adding a 3rd it for testing the draft feature set

what I did do was add better selectors throughout and added tests for the detail page. I think if we spun a separate ticketo up for the drafting process that would be okay, and with the other changes in here that should be a quite a bit easier to do (I hope)

**Comment by emilyjablonski** [comment]
Reviewing the code today, but can you take a look at the failing tests?

**Review by seanmalbert — APPROVED** [review]
@YazeedLoonat ,
I'm approving this, because it gives us coverage we don't have and something to build off of. There is the question of how we want to target the fields. In one of her PRs @emilyjablonski is using a test id to target the fields, so I think we should align on that. I also think it would be useful to break out filling the fields into more reusable cy commands, so we can better focus on pieces of the form. I'll leave it to you and Emily if you want to do those things here or in a follow-up issue.

**Review by emilyjablonski — APPROVED** [review]
🥳 `

**Pull request merged**
