### PR TITLE
feat: MA-3752 add SHOW_MANDATED_ACCOUNTS flag

### PR DESCRIPTION
**Pull request by cade-exygy**
# Pull Request Template

## Issue Overview
https://github.com/bloom-housing/bloom/issues/3752

This PR addresses #3752 

- [ ] This change is a dependency for another issue: Yes, the Mandated Accounts epic

## Description

Adding a feature toggle for the Mandated Accounts feature

## How Can This Be Tested/Reviewed?

on localhost: 

- add the env variable: `SHOW_MANDATED_ACCOUNTS` to you `.env' to bloom/public
- run the app
- You can make a local code change that relies on the flag, for example you could log out `process.env.showMandatedAccounts && 'hello world'`

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.
- Did the above review instructions
- @emilyjablonski are there any unit or e2e tests we can add for this?
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by emilyjablonski** [comment]
@cade-exygy This looks great! Just a few notes on PR process here, happy to also hop into a huddle if helpful
* The title of the PR should be in the conventional commit format the same way the commits are. When you click merge the PR title is auto-populated and we just want to make sure whatever message gets merged is in the right formatting.
* Do you mind filling out the PR checklist? Some of them which are less relevant here (ie I tested on mobile) you can leave blank at your own discretion

**Comment by emilyjablonski** [comment]
@cade-exygy Sorry just some additional clarity here! Here is the conventional commit documentation: https://www.conventionalcommits.org/en/v1.0.0/

It must start with one of the tags, so it should begin with `feat: ....`

**Comment by cade-exygy** [comment]
> @cade-exygy Sorry just some additional clarity here! Here is the conventional commit documentation: https://www.conventionalcommits.org/en/v1.0.0/
> 
> It must start with one of the tags, so it should begin with `feat: ....`

thanks for linking that! Does the title look okay now?

**Comment by emilyjablonski** [comment]
@cade-exygy Perfect! And I think this one is good to go with only one review, so I'll pop the `ready to merge` tag on there and you can squash and merge.

**Review by emilyjablonski — APPROVED** [review]

**Pull request merged**
