### PR TITLE
Add application form config to DB schema

### PR DESCRIPTION
**Pull request by pbn4**
Addesses https://github.com/bloom-housing/bloom/issues/747 - Add the backend object for Application Form Config (1:1 with listings?) and rationalize with Listings as appropriate

### CODE REVIEW

**Comment by jaredcwhite** [comment]
@pbn4 This looks good to me. I feel like maybe we're missing a step though (pardon the pun 😉)…

My understanding is that there needs to be a "master" config somewhere that is essentially duplicated when a new listing is created. It was something we deliberated for some time back when this was all getting hammered out, so I don't think it ever got fully spec'd out. But we need some kind of template mechanism whether that is something living in the database or defined in a backend config file somewhere, so when a listing gets created it inherits that form config.

**Comment by jaredcwhite** [comment]
Hey @pbn4, let me know if my comment above makes sense…I don't recall how detailed the original spec was (if at all) and we might need to double-check it's heading in a direction we still want…

**Review by jaredcwhite — CHANGES_REQUESTED** [review]
Hey @pbn4, let me know if my comment above makes sense…I don't recall how detailed the original spec was (if at all) and we might need to double-check it's heading in a direction we still want…

**Comment by pbn4** [comment]
@jaredcwhite Definitely makes sense, I switched over to other work but I will apply your comments shortly.

**Comment by kathyccheng** [comment]
At this point, we'll want to support having multiple listings with applications running at the same time. These listings are likely to have different preferences. Also, we'll be starting our first San Mateo County application which will have 3 questions that are different than Alameda's so we want to make sure we're serving the right questions, it might be worthwhile to think about having a county default set of questions.

**Comment by kathyccheng** [comment]
Front end refactoring addressed in #1130 and #1129

**Comment by pbn4** [comment]
I'm closing this PR since it's long incompatible with existing codebase and current listings will address variable preferences with   metadata attached to listing model.

**Pull request closed without merging**
