### PR TITLE
fix: prevent listings without AMI charts

### PR DESCRIPTION
**Pull request by KrissDrawing**
This PR addresses [#692](https://github.com/metrotranscom/doorway/issues/692)

- [x] Addresses the issue in full
- [ ] Addresses only certain aspects of the issue

## Description

It's a change from task comment. It will throw an error when trying to add unit without ami chart

## How Can This Be Tested/Reviewed?

Create new unit without touching `AMI Chart` dropdown.
Try to save -> It should throw validation error (prevent from saving)

## Author Checklist:

- [ ] Added QA notes to the issue with applicable URLs
- [ ] Reviewed in a desktop view
- [ ] Reviewed in a mobile view
- [ ] Reviewed considering accessibility
- [ ] Added tests covering the changes
- [ ] Made corresponding changes to the documentation
- [ ] Ran `yarn generate:client` and/or created a migration when required

## Review Process:

- Read and understand the issue
- Ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review after the updates

### CODE REVIEW

**Comment by mcgarrye** [comment]
I think this needs more discussion with product. Units can be added without AMIs and hiding the table but not changing how the Household Maximum Income section and Listings page/search to Listing flow confusing.
Cases to note with the change this PR makes:
- A unit is added without AMI chart and without fixed/percent rent and other fully filled out units exist. This causes n/a's on the Listings page and then when the user goes to the listing they don't see the unit at the top with the other units. Household Maximum Income has a strange NaN% column.
- A unit is added without AMI chart but with fixed/percent rent and other fully filled out units exist. This unit info is filled in on the Listings page and then when the user goes to the listing they don't see the unit at the top with the other units. Household Maximum Income has a strange NaN% column.
- Only units without AMI charts are added. The table appears with no label at the top. Household Maximum Income has an empty table.
- Only units without one AMI percent are added. The table appears with no label at the top.

This creates a confusing user experience where the user may not understand what units are available, what the rent is for those units and if they are eligible.
@sarahlazarich

**Comment by sarahlazarich** [comment]
Good points @mcgarrye - let me confirm with Izzie if we should just block this entirely. I'll follow up.

**Comment by ColinBuyck** [comment]
Looks like partners cypress tests are failing. Do you mind checking this out @KrissDrawing?

**Review by mcgarrye — APPROVED** [review]
LGTM

**Pull request merged**
