### PR TITLE
Add warning when pending migrations are detected

### PR DESCRIPTION
**Pull request by pbn4**
Closes https://github.com/bloom-housing/bloom/issues/340

### CODE REVIEW

**Review by software-project — APPROVED** [review]
LGTM 👍

**Comment by bencpeters** [comment]
> Looks good generally, but I'm wondering if we want to be more assertive here and exit out on startup with an error if things aren't in sync, instead of just a warning that someone could miss? Is that too much? I could be convinced either way.

That seems easier to check to me - a single test visit post deployment would reveal that the API was down. Since the migrations are presumably necessary for the API to run correctly anyway, it's really a choice between "very noticeable error on deploy" or "variable/unpredictable errors later". The only "advantage" to the non enforcement approach seems to me to be that the API _might_ degrade _somewhat_ gracefully (e.g. parts of the functionality that have nothing to do with the missing migration might still work), but I don't think that's a great thing to rely on, personally.

**Comment by bk3c** [comment]
Ok, I made the change to not start up if there are pending migrations. @pbn4 does that look ok to you?

**Comment by pbn4** [comment]
LGTM Thanks @bk3c

**Pull request merged**
