### PR TITLE
fix: no application message and loading spinner working

### PR DESCRIPTION
**Pull request by ColinBuyck**
# Pull Request Template

## Issue Overview

This PR addresses #issue

- [x] This change addresses only certain aspects of the issue

## Description
This PR addresses #2396 

This fix displays a message to the user when they haven't completed any applications and provides a link to view listings. 

Additionally, based on my testing the loading spinner was showing initially but there was a slight delay from when it would disappear and when the listings would show. This seemed to be because the loading state would update before the application state updated so by running the spinner until applications length property is defined as well this delay is reduced. On slower networks, however, the delay is still very noticeable.  

## How Can This Be Tested/Reviewed?

Both the "no applications" message and the loading spinner can be tested by going to the My Applications page with the admin@example account which has no applications. The loading spinner can also be tested on the same page with the test@example account which has multiple applications

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by emilyjablonski** [comment]
👋 I think this is ready for review based on the assigned reviewers - just a couple reminders! Make sure in the PR template you (1) add the issue number and (2) walk through the checklist and check anything relevant, and then (3) add the `needs review(s)` label to surface it to the team.


https://user-images.githubusercontent.com/65367387/161135308-aa5bc946-6acd-4cfe-a1e6-8d7c0282afef.mov

In terms of the AC, I'm seeing a delay between the loading spinner disappearing and the applications appear. The above image was from testing on the deploy preview. I noticed the delay without any throttling, but it is much easier to test and see if you throttle the network with the dev tools. My initial hypothesis is that it may be we want to check `!applications?.items.length` instead of `!applications` for the `<LoadingOverlay>` component.

**Comment by ColinBuyck** [comment]
Thank you for the reminders! The PR template should be filled out correctly now. In terms of this issue, I added the length adjustment but the delay is still pretty prevalent. I can keep exploring different ideas if that'd be helpful.

Also, do you know of a way to effectively throttle the network on localhost? When I tried it with fast 3G, the page was on track to load in about 10 minutes so I had to test on the netlify preview.

**Review by emilyjablonski — APPROVED** [review]
I'm still seeing the loading delay, but I think it's going to be really challenging to fix before we can understand why the local stack isn't throttling correctly. I'm good to merge this with the no applications fix, and we can continue investigating the delay in another issue 👍

**Review by seanmalbert — CHANGES_REQUESTED** [review]
@ColinBuyck and @emilyjablonski ,

I looked into this a little more and I discovered two things:
1. I believe that throttling actually works fine locally, it's that in development mode the resources are so large that under throttling the site will never realistically load. There are steps we can do to mitigate this, but I'm not sure how much it's worth it since we can still test with throttling locally by first running `yarn build` in `sites/public` and then `yarn start`. This makes the resources considerably smaller and better mimics what we're doing in the cloud environments.
2. In doing this, it was easier to see what is going on. We have the `LoadingOverlay` component and that's waiting for applications to load and does so correctly. However, that's wrapping `StatusItemWrapper`, which upon receiving applications, queries listings and this is the result in the delay between the loading overlay finishing and applications appearing. It seems that by moving `LoadingOverlay` to `StatusItemWrapper` and waiting for listings to load, we will have our bases covered.

**Review by seanmalbert — CHANGES_REQUESTED** [review]
@ColinBuyck ,

From our last pair on this, here are the changes we discussed:

1. In a new types file under `sites/public/pages/account` export a new interface that extends Application with a new key to house the full listing. This will be used in `sites/public/pages/account/applications.tsx` and `sites/public/pages/account/StatusItemWrapper.tsx` Something like:
  ```
interface AppWithListing extends Application {
    fullListing?: Listing
}
   ```
2. in applications.tsx, update the applications useState type to be `AppWithListing[]`
3. add a new state to keep track of when listings are loading, this should default to true
4. in the return of the applications service where `setApplications` is set, update that to be `apps.items` since the new type is now `AppWithListing[]`
5. We can simplify the second useEffect you have to fetch listings and map them onto the applications. This is most easily done by using Promise.all in conjunction with applications.map. This will roughly look like:
```
void Promise.all(applications.map(async (application) => {
       // fetch listings in here and set full listing on application
       return application
    })
).then((res) => {
    // set listing loading to false
    // set applications
    // set loading to false
}
```
6. at the top of this useEffect hook, we want to return (not continue) if applications is undefined or if applications are defined and listings are not loading
7. at this point you should just be able to set the isLoading prop on LoadingOverlay to `loading`
8. Where applications is getting mapped and returning `StatusItemWrapper`, this can be cleaned up to directly map applications with `key` and `applications` being the only two props passed to `StatusItemWrapper`
9. clean up the check for `noApplicationsSection` below
10. In StatusItemWrapper, set the application key in `StatusItemWrapperProps` to be of type  `AppWithListing`, and get rid of the `listing` key.
11. update the prop values sent to `StatusItem` so that listings are now on the application

Let me know if you need clarity on any of those items.

**Comment by ColinBuyck** [comment]
The most recent commit should reflect all of these directions except for the first and ninth. 

1 - Since the types cannot be alone in a file within pages they seemed more appropriate to be in the file directly than potentially alone in the src file unless it would be a helpful precedent to clean up other files.

9 - I believe the no applications check requires the length check on applications since the applications state is still defined even when none are found. If this was a must-have, then I it would be possible to perform this check in the useEffect to avoid defining applications if none are found.

**Comment by ColinBuyck** [comment]
Note: The Cypress test is failing since dev has "Open" for listing status in the partners listing table instead of "Accepting Applications" which the cypress test is looking for.

**Review by seanmalbert — APPROVED** [review]
Looks good, @ColinBuyck . I fixed the partner cypress tests as well.

**Comment by seanmalbert** [comment]
@ColinBuyck , can you please write QA notes for review on the connected issue. Then we're good to merge.

**Comment by ColinBuyck** [comment]
@seanmalbert Just added them. Thanks!

**Pull request merged**
