### PR TITLE
fix: cannot remove some fields in listings management

### PR DESCRIPTION
**Pull request by emilyjablonski**
# Pull Request Template

## Issue Overview

This PR addresses #2371

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

You can now remove a leasing agent address in a draft or published state, & a photo and a building address in a draft state.

For an address to save, it must be a valid address (street, city, state, zip).

## How Can This Be Tested/Reviewed?

Create a new listing and save it as a draft with a building address, photo, and leasing agent address. Then remove the fields and ensure they are removed.

Edit an existing published listing and try to remove building address or photo - you should not be able to, it validates them as required fields, but you should be able to remove the leasing agent address. Also check here that removing just one of the building address fields only highlights that field in red (previously it was highlighting every field in the address, even ones that were valid).

Possible Cypress followup: https://github.com/bloom-housing/bloom/issues/2454
## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by dominikx96 — CHANGES_REQUESTED** [review]
@emilyjablonski I've found a couple of things:

1. I don't see any error message near the listing photo field (only alert at the top): https://share.getcloudapp.com/7KuqkOdv

2. When I save empty fields, I see just labels and empty values. On the initial state (when you create a new listing and fields are empty) there are "None" labels.

https://share.getcloudapp.com/2Nuv74Jb
https://share.getcloudapp.com/qGurx2jn

Empty values on initial save (with "none" labels):
https://share.getcloudapp.com/bLux5EAR

3. When I fill the "LEASING AGENT ADDRESS" section, then edit - I see empty fields
Video: https://share.getcloudapp.com/llu6dq2b

**Review by YazeedLoonat — APPROVED** [review]
LGTM

**Comment by emilyjablonski** [comment]
@dominikx96 
* Missing photo error label fixed
* Missing "None" field is fixed, I made it so if there is no address it just says "none" instead of none for every field
* I couldn't reproduce this but in your video from what I can see the leasing agent details section is filled out but I can't see if the address is, and then the address field is empty, lmk if I have this wrong!

**Review by seanmalbert — CHANGES_REQUESTED** [review]
@emilyjablonski ,
From our conversation at stand-up, I think we want to show validation on the frontend, if a user enters a partial address without all of the required fields. This is ok even when saving as a draft. Maybe we should have error text that lets the user know that partial addresses are not acceptable.

**Comment by emilyjablonski** [comment]
New changes will show an error message "Cannot enter a partial address" on all address fields if some of the required fields are filled out but not all of them, even when saving as draft on non-required address fields. You can still add and remove addresses. An address is removed when all four required fields are emptied.

**Review by seanmalbert — APPROVED** [review]
LGTM, thanks for the updates!

**Pull request merged**
