### PR TITLE
feat: migrate afs job off of redis

### PR DESCRIPTION
**Pull request by ludtkemorgan**
## Issue Overview

This PR addresses #3191 

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

The current setup for the application flagged sets cron job is never getting hit. This is due to its reliance on the bull nestjs library that uses redis. For an unknown reason the redis setup in heroku is connecting but nothing is getting set in it. To solve this problem this PR removes the dependence on redis and uses nestjs's scheduler functionality.

Things to note:
- The cron frequency can be set as a .env variable called `AFS_PROCESSING_CRON_STRING`
- Due to us using 3 dynos in our production environment if we were to use the nestjs cron jobs without any changes it would get run three times simultaneously and potentially crash. To solve this I have added a step where a random number between 0 and 59 is put at the beginning of the cron string. This makes it so it will run at a random second at the cron run time and theoretically the jobs will be run at a staggered interval. Also when the cron job is triggered a new timestamp is saved to the db to indicate the last run time of the job. Before running it checks to make sure that that the last run time is over 5 minutes old.
  - Sample example: Cron job is set to run at midnight everyday. dyno 1 randomly selects 24 as the seconds, dyno 2 selects 11, and dyno 3 selects 53.
    - dyno 2 triggers first at 12:00:11. It checks the db and last run was almost 24 hours ago.
    - dyno 2 updates the "last run time" to 12:00:11
    - dyno 2 runs the processing
    - dyno 1 triggers at 12:00:24. It checks the db and last run was 13 seconds ago so it doesn't run
    - dyno 3 triggers at 12:00:53. It checks the db and last run was 42 seconds ago so it doesn't run

## How Can This Be Tested/Reviewed?

The easiest way to test this is to add a new record to your .env file for backend core for `AFS_PROCESSING_CRON_STRING`. Sample `AFS_PROCESSING_CRON_STRING="0,10,30 * * * *"` (runs every hour at 0, 10, and 30 minutes). When you start up the application you should see logging of "running the Application flagged sets cron job" to appear within the minute you set in the environment variable. I'd recommend testing a couple of variations of the cron string. Note that you need to restart the application if you change the .env file.

The database table of `cron_job` should also be added with a new entry of name `AFS_CRON_JOB` after the cron job first gets triggered. Make sure the last run time is updated correctly

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by emilyjablonski** [comment]
Thank you for the great documentation!! I have a quick question, I think I'm not sure why the randomized seconds is necessary, does it not work to have the first job that gets there set the db flag, and have each job just check and make sure it's been at least five minutes?

**Comment by ludtkemorgan** [comment]
> Thank you for the great documentation!! I have a quick question, I think I'm not sure why the randomized seconds is necessary, does it not work to have the first job that gets there set the db flag, and have each job just check and make sure it's been at least five minutes?

Without the random seconds the cron jobs will all get triggered at the exact same time. For example if the cron job is set for `0 0 * * *` (every day at midnight) all three will get triggered exactly at midnight to the second. That means that they will all try to update at the exact same time and not know that the other two are also trying to update the last run timestamp.

This is also just a theory that this random seconds method will work properly. We'll need to test it in the prod environment to actually make sure it's working as expected

**Review by YazeedLoonat — APPROVED** [review]
LGTM

**Comment by YazeedLoonat** [comment]
@ludtkemorgan could you please add the new env to the .env template please!

**Comment by ludtkemorgan** [comment]
> @ludtkemorgan could you please add the new env to the .env template please!

Added!

**Pull request merged**
