### PR TITLE
feat: add Programs section to listings management

### PR DESCRIPTION
**Pull request by emilyjablonski**
# Pull Request Template

## Issue Overview

This PR addresses #1868
- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Adds the Programs section to listings management. It's identical to the Preferences section. Also fixes an existing bug with Preferences where if you opened the drawer, deleted an already select preference from the draggable list, then opened the checkboxes, the deleted checkbox would still be checked.

Still waiting to hear from Kathy what the titles of the Programs should be in LM since we are currently showing just the questions, and have no titles. Will update seeds when I get those.

## How Can This Be Tested/Reviewed?

Add, remove, and reorder both preferences and programs. Ensure they appear on the detail page as well.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [x] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [x] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by seanmalbert — CHANGES_REQUESTED** [review]
Hey @emilyjablonski ,
Overall this looks good and I like the use of SelectAndOrder. I am seeing a maximum update depth exceeded that looks to be caused by the useEffect hook that calls `setUniqueListingData`. You'll also need to resolve the conflicts caused by the updates to preferences, which should mostly entail adding in the jurisdictional filter logic (which should remove the need for that useEffect hook). Let me know if you run into issues resolving merging in the latest with those preference updates.

It would be great to get integration tests with this piece, but from your comments on #2103 , it doesn't look like it's ready to merge yet. We don't have to wait on that when this is ready to merge, but I think we should keep the issue tied to this PR open until we have a follow-up PR with those tests.

**Review by seanmalbert — APPROVED** [review]
This looks and is working great, @emilyjablonski! The only thing I see is in the updates in the backend for programs and filtering by jurisdiction. `preferences` is used instead of `programs`. It works as it is now, because it's using the programs repository and just naming it "preferences" and for consistency we should update it.

**Comment by dominikx96** [comment]
@emilyjablonski I've noticed 2 problems:

1) When I **open** the programs drawer and delete one of them. The `jurisdiction` field resets.
When you try to delete it from the list in the `Housing Programs` everything works as expected.

2) When I click on the `save` button (when a drawer is opened) and `jurisdiction` field is
Partners Portal 2021-11-04 at 12 59 05 PM
 empty, I'm getting:

**Review by dominikx96 — CHANGES_REQUESTED** [review]
@emilyjablonski I've noticed 2 problems:

1) When I **open** the programs drawer and delete one of them. The `jurisdiction` field resets.
When you try to delete it from the list in the `Housing Programs` everything works as expected.

2) When I click on the `save` button (when a drawer is opened) and `jurisdiction` field is empty, I'm getting:
Partners Portal 2021-11-04 at 12 59 05 PM

**Comment by seanmalbert** [comment]
@dominikx96 , I confirmed that @emilyjablonski fixed the issue that you raised. We're good to go!

**Pull request merged**
