### PR TITLE
Rename and relocate packages

### LINKED ISSUE #528: [RFC] Front-end package and directory re-organization
Following recent discussions with @akegan and @james-wills-sf about making it easier to package common code for import rather than maintaining it in the reference implementation, I'd like to propose the following package and directory reorganization:

- Change the `apps/` top level directory to `sites/`, and generally change our naming to call those things sites rather than apps. The main reason for this is to avoid any potential confusion between "apps" and Applications, which will only get worse over time. I'm open to a name other than "sites", if anyone has a better idea.

- Rename the `@bloom-housing/core` package to be `@bloom-housing/site-core`. This will make it the clear home for common front-end code in addition to interfaces, and we can move logic that's shared between the public and partners apps there from ui-components (other than actual ui-components), plus aim to refactor as much as is reasonable there over time.

- Add `@bloom-housing/site-public` and `@bloom-housing/site-partners` packages to hold logic that we expect to be specific to one site or the other, but more general than the reference implementation. For example, the ApplicationConductor (or successor) will probably be unique to public, but it unlikely to be a point of customization so we're better of having it imported rather than have to maintain/diff/etc from the reference implementation to production sites. FWIW, I expect the partners package would grow to be substantially bigger than public over time, both in terms of code and dependency load size, so this gives us a way to keep the public site slimmed down but still have a place to abstract "core" code more cleanly from each reference ~~app~~ site.

I don't think this would change anything on the back-end in the short term.

Thoughts, @jaredcwhite, @dominikx96, @software-project, @bencpeters?

### PR DESCRIPTION
**Pull request by jaredcwhite**
Resolves #528 

* Remove shared/core and services/listings and move ui-components to top-level
* Put type definitions for frontend in `backend/core/types`
* Rename apps/\*-reference to sites/\*

### CODE REVIEW

**Comment by jaredcwhite** [comment]
FYI this is likely not going to build because of all the directory changes. Also, if folks feel like the autogenerated frontend types should be located somewhere other than `backend/core/types`, feel free to suggest alternatives.

**Comment by kathyccheng** [comment]
@jaredcwhite do you need reviews from @software-project @pbn4 @dominikx96 to move this forward? I know this is one of those we don't want to leave hanging too long

**Review by software-project — CHANGES_REQUESTED** [review]
Nice work and a positive change. I did a quick tests and only little thing I found was a reference to old listings service in `dev:all` yarn task. 👍

**Comment by jaredcwhite** [comment]
I got jest tests working in ui-components, and I made the package.json changes you pointed out @software-project.

**Comment by jaredcwhite** [comment]
Still some CircleCI tests failing like for the public/partners apps…will investigate.

**Comment by pbn4** [comment]
@jaredcwhite I'll more backend/core/types to ui-component in a separate PR

**Comment by jaredcwhite** [comment]
All tests passing now! (except for Netlify)

**Comment by pbn4** [comment]
@jaredcwhite What is the ETA for this?

**Pull request merged**
