### PR TITLE
fix: add backend url validation

### PR DESCRIPTION
**Pull request by KrissDrawing**
# Pull Request Template

## Issue Overview

This PR addresses #3972 

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Adds backend url validation for URL fields. It should only affect listing create / edit as rest uses frontend validation, so it probably won't make into backend validation. But make sure they still work.
There is an issue with `buildingSelectionCriteria` when it sends some redundant fields when we manually remove url (so edit, and remove link and click save) it works fine on delete click tho.

## How Can This Be Tested/Reviewed?

Create / edit listing with digital application -> put invalid url into custom url field (without protocol and / or invalid). On submit it should populate error for it.
make sure rest fields are working:
- listing create -> open House (to disable FE validation OpenHouseForm.tsx -> comment out `type='url'` line 154)
- settings -> preference url and option url ( to disable FE validation -> PreferenceDrawer.tsx -> comment out `type='url'` line 233 and 515)

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by mcgarrye** [comment]
I think it would be worth while to add this validation to all flows that send a url. That way our API is protected in the case of a direct call.

**Comment by KrissDrawing** [comment]
@mcgarrye you're right, i've added validation for buildingSelectionCriteria. Not sure if we have any other url field (at least couldn't find any)

**Comment by mcgarrye** [comment]
> rotocol and / or invalid). On submit it should populate error for it.
> make sure rest fields are working:

Can you update the description to match the new functionality?

**Review by mcgarrye — APPROVED** [review]
Stops urls without `https` or `http` and incorrectly formatted urls

**Pull request merged**
