### PR TITLE
fix: migration updates

### PR DESCRIPTION
**Pull request by YazeedLoonat**
Updates to migration:

this should make running `yarn db:migration:run` work

### CODE REVIEW

**Comment by emilyjablonski** [comment]
Screen Shot 2022-08-19 at 4 18 00 PM
Is the application working on your end here?

**Comment by emilyjablonski** [comment]
Also seeing issues in the listing form that I don't see from a reseed
Screen Shot 2022-08-19 at 4 18 57 PM

**Comment by YazeedLoonat** [comment]
Hey @emilyjablonski I think I got this update correctly, lemme know what you think

**Comment by emilyjablonski** [comment]
Screen Shot 2022-08-22 at 11 55 13 AM
I'm still seeing this, are you not seeing this locally on your end?

**Review by emilyjablonski — APPROVED** [review]
Looks great!!! Thank you so much!

**Pull request merged**
