### PR TITLE
(fix): 404 issues in my application and settings

### LINKED ISSUE #1151: Account Settings Bug
When I click on Account Settings from the Account dropdown, it takes me to the Account Settings page.
But when I click on Account Settings from My Dashboard, I get a 404

### PR DESCRIPTION
**Pull request by emilyjablonski**
Fixes #1151 and #1152

* Account Settings from the dashboard would 404
* Clicking on a link to an individual application from My Applications would 404

Use the Netlify preview to test!

### CODE REVIEW

**Comment by emilyjablonski** [comment]
They're all working on the deploy preview! :)

**Review by jaredcwhite — COMMENTED** [review]
Cool! One question: you deleted the file `sites/public/pages/account/settings.tsx`, was that intentional?

**Comment by emilyjablonski** [comment]
Yep it wasn't in use anywhere ¯\_(ツ)_/¯ @jaredcwhite

**Comment by emilyjablonski** [comment]
Checked in w Jared offline, said it looks good to go!

**Pull request merged**
