### PR TITLE
Add criminal background & more translated strings

### LINKED ISSUE #103: Add "criminal background" to Additional Eligibility Rules
See attached screenshot from previous codebase:

Screen Shot 2019-11-22 at 4 01 02 PM

### PR DESCRIPTION
**Pull request by jaredcwhite**
Fixes #103

### CODE REVIEW

**Comment by bk3c** [comment]
Code all looks good to me and tests fine locally.

@jacchau can you come up with some appropriate test text to insert before we merge, since it looks wrong currently being blank?

**Comment by jaredcwhite** [comment]
> Code all looks good to me and tests fine locally.
> 
> @jacchau can you come up with some appropriate test text to insert before we merge, since it looks wrong currently being blank?

I think a couple of the listings have some content, one is blank. I forget which one.

**Comment by jacchau** [comment]
@jaredcwhite Here is test text that we can use from a SJ Charities listing:
"A criminal background investigation will be obtained on each applicant.  As criminal background checks are done county by county and will be ran for all counties in which the applicant lived,  Applicants will be disqualified for tenancy if they have been convicted of a felony or misdemeanor.  Refer to Tenant Selection Criteria or Qualification Criteria for details related to the qualification process."

**Comment by jaredcwhite** [comment]
Added the additional text to Triton. Merging.

**Pull request merged**
