### PR TITLE
feat: seeds button uptake

### PR DESCRIPTION
**Pull request by jaredcwhite**
## Issue Overview

This PR addresses #3595 

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This PR swaps out all UIC buttons with Seeds buttons in the Core applications. Note that this doesn't address any buttons which may be embedded within other UIC components.

## How Can This Be Tested/Reviewed?

Visit pages in the Public and Partners sites. Ensure that the buttons work and aren't broken. I noticed some translations have odd capitalization, which means you can now tell (because the old buttons were ALL CAPPS), but I would recommend addressing those in followup PRs.

**NOTE**: there are two Cypress tests for Partners which I cannot figure how to resolve. The error messages are confusing and don't make sense. Also note: the jest-shared-helpers test is failing, but that's due to an apparent TypeScript issue coming from Seeds, so if we want to resolve that we'll need to address in a separate issue/PR in that repo.

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by ludtkemorgan** [comment]
@jaredcwhite one way we can solve the "jest-shared-helpers" failing test is to change the tsconfig.json in the shared-helpers to have this line `"noImplicitReturns": false,`. But that might have a bigger impact than just fixing it in seeds

**Review by ludtkemorgan — COMMENTED** [review]
No issues found so far, but two notes:

- There is at least one usage of the ui-components button in a test file - `StatusBar.test.tsx`
- The failing cypress tests appear to be failing because the TextArea component is unable to be typed in by Cypress. Don't know why that would be happening with your changes. I'll continue to investigate it today

**Review by ludtkemorgan — APPROVED** [review]
This looks good to me so I'm approving it. The error that is happening for the textarea is because apparently it is partially covered by the save button. But I don't know why cypress thinks that. Here is the error:

image

I am able to get past this by changing the type step to this. But we should probably look into why Cypress thinks the button is covering the textarea
```
    cy.getByTestId("preference-description").type("Preference Description", {
      force: true,
    })
```

**Comment by jaredcwhite** [comment]
Thanks @ludtkemorgan for looking into that! Weird stuff. We'll have to keep an eye on it.

**Comment by jaredcwhite** [comment]
> one way we can solve the "jest-shared-helpers" failing test is to change the tsconfig.json in the shared-helpers to have this line "noImplicitReturns": false,. But that might have a bigger impact than just fixing it in seeds

Hmm, yeah we might just have to see if we can patch that in Seeds directly.

**Comment by emilyjablonski** [comment]
@jaredcwhite Any luck on the tests here?

**Comment by jaredcwhite** [comment]
@emilyjablonski I haven't spent any more time on it. Still stumped. 🤷🏻‍♂️

**Comment by jaredcwhite** [comment]
Success! I was able to fix the issues with the Cypress partners tests (and also unit tests). The one remaining failing test was the issue we already identified which requires a fix in Seeds. (The other backend failure seems to be a fluke…a previous test run was successful.)

**Pull request merged**
