### PR TITLE
fix: upgrade all nest dependencies

### PR DESCRIPTION
**Pull request by ludtkemorgan**
# Pull Request Template

## Issue Overview

This PR addresses #3319 

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This PR upgrades all nestjs packages to the latest version. 

- Note the nextjs axios package was not upgraded as that requires some additional library upgrades so I will do that as a separate PR.

## How Can This Be Tested/Reviewed?

Minimal changes were needed and no tests broke, but it would be nice to do a high level testing of the get and post/put endpoints. So testing the main public pages along with the partner pages.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by emilyjablonski** [comment]
I'm not able to apply for a listing on the deploy preview but the same listing is working on dev (looks like it is never fetching)

**Comment by emilyjablonski** [comment]
https://github.com/bloom-housing/bloom/issues/3468 The issue I think is unrelated to what was happening here

**Comment by ludtkemorgan** [comment]
@emilyjablonski good find. Since this PR doesn't have any front-end changes I'd recommend testing it either locally or just in dev (it is deployed to dev environment at the moment)

**Review by YazeedLoonat — APPROVED** [review]
LGTM

**Review by ColinBuyck — APPROVED** [review]
LGTM 🪆

**Pull request merged**
