### PR TITLE
fix: replace usage of sanitize-html

### PR DESCRIPTION
**Pull request by kramduckner**
# Pull Request Template

## Issue Overview

This PR addresses #issue

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

A [recent pr](https://github.com/bloom-housing/bloom/pull/2914) replaced the dompurify library (which sanitizes html) with sanitize-html which broke DAHLIA (attached screenshot). This fix uses the <Markdown /> component (which we already have access to via [markdown-to-jsx](https://www.npmjs.com/package/markdown-to-jsx) lib) which does some basic sanitization - although it's a bit hard to find out exactly what sanitization it does when the disableParsingRawHTML is set to false, it at least removes script tags! 

Just because this is blocking uptakes on dahlia, it'd be nice to fast track this! I'm open to reworking this with a different, longer-term solution. Also open to any other quick, potentially temporary fixes.

Screen Shot 2022-08-10 at 3 15 25 PM

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

- Ensure that previews work from partners (it doesn't crash).
- Compare MultiLineAdress components in storybooks (should have a 1:1 visual parity)
- Check a couple examples of <Multiline/> usage in listings (e.g. the component that shows the address in the map on the detailed listing page)
- Updates don't introduce any breaking changes

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by seanmalbert — COMMENTED** [review]
Hey @kramduckner ,

I know you got a WIP label on here so I won't comment on the cleanup that needs to happen in what you added (well, aside from that). I'm down with the change as long as there aren't any visual breaking changes. Can you make sure @dominikx96 reviews this update, since he made the original updates to MultiLineAddress.

**Comment by kramduckner** [comment]
Thanks @seanmalbert !

That sounds good. Ready for clean up cleanup comments! I also realized I don't actually know how to test listing previews on a netlify deploy preview - looks like I can't create an account and I think one has to be logged in to public to view listing previews? But this also feels like it's in the territory of the code speaking for itself in terms of stability since we already use that npm package in both bloom and dahlia.

**Review by dominikx96 — CHANGES_REQUESTED** [review]
@kramduckner from the public and partners looks great! I just noticed 2 things:
- there is a `"@types/sanitize-html": "^2.6.2"` package, it should be removed along with the `sanitize-html`.
- In a storybook you can notice `undefined` values - can you check why it renders `undefined` as a string?
Screenshot 2022-08-12 at 17 59 14

Screenshot 2022-08-12 at 17 59 21

**Comment by kramduckner** [comment]
@dominikx96  good catch on the types! I'll remove that. The undefined stuff is weird. It's the way template literals are being parsed through these libraries. I'd like to rework this component and improve that (I don't like ever showing undefined to an end user!) - but I think that should require some input from design (e.g. do we even want to support an address without a city? If there's no state, should we just omit that whole line?), and since this is a blocker, I just tried to make the functionality 1:1 with what was there before. What do you think about just making sure it is 1:1 with what was there, and file a new ticket to handle these undefined states better?

**Review by seanmalbert — APPROVED** [review]
lgtm

**Pull request merged**
