### PR TITLE
CSV encoder

### PR DESCRIPTION
**Pull request by pbn4**
Closes https://github.com/bloom-housing/bloom/issues/625

### CODE REVIEW

**Comment by pbn4** [comment]
This is what it returns right now:

```
"Application Number","Primary Applicant First Name","Primary Applicant Middle Name","Primary Applicant Last Name","Primary Applicant Date of Birth","Primary Applicant Email","Primary Applicant Phone","Primary Applicant Phone Type","Primary Applicant Additional Phone","Primary Applicant Additional Phone Type","Primary Applicant Preferred Contact Type","Primary Applicant Residence Street Address","Primary Applicant Residence City","Primary Applicant Residence State","Primary Applicant Residence Zip","Primary Applicant Mailing Street Address","Primary Applicant Mailing City","Primary Applicant Mailing State","Primary Applicant Work Street Address","Primary Applicant Work City","Primary Applicant Work State","Primary Applicant Work Zip","Application Submission Date","Application Submission Language","Application Submission Type","Alternate Contact First Name","Alternate Contact Last Name","Alternate Contact Type","Alternate Contact Other","Alternate Contact Agency","Alternate Contact Email","Alternate Contact Phone","Alternate Contact Street Address","Alternate Contact City","Alternate Contact State","Alternate Contact Zip","Household Size","Household First Name","Household Middle Name","Household Last Name","Household Relationship","Household Date of Birth","Household Annual Income","Household Monthly Income","Receives Vouchers or Subsidies","Requested ADA Unit","Claimed Live Work Preference","Opted Out Live Work Preference","Requested accessibility"
"46d1f0c0-1821-411e-a56e-5ffe34c3f3a2","Michal","Midname","Plebanski","03/04/1993","michalp@airnauts.com","(555) 555-5555","work","Yes","Home","email,phone,letter","A, 4","S","AK","","B, 5","C","AR","Work","City","AZ","","Fri Sep 11 2020","TBD","TBD","M","P","friend","","TBD","mp@example.com","(111) 111-1111","M","C","DC","","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","vision,hearing"
"8e35121a-cf7f-48f0-9a10-8b6c4bfa5746","Michal","Midname","Plebanski","03/04/1993","michalp@airnauts.com","(555) 555-5555","work","Yes","Home","email,phone,letter","A, 4","S","AK","","B, 5","C","AR","Work","City","AZ","","Fri Sep 11 2020","TBD","TBD","M","P","friend","","TBD","mp@example.com","(111) 111-1111","M","C","DC","","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","vision,hearing"
"6f052bf2-a243-4aa8-b619-00f663ce11f2","Michal","Midname","Plebanski","03/04/1993","michalp@airnauts.com","(555) 555-5555","work","Yes","Home","email,phone,letter","A, 4","S","AK","","B, 5","C","AR","Work","City","AZ","","Fri Sep 11 2020","TBD","TBD","M","P","friend","","TBD","mp@example.com","(111) 111-1111","M","C","DC","","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","vision,hearing"
"ead039cd-a98e-4564-bd4f-509a96a9a003","Michal","Midname","Plebanski","03/04/1993","michalp@airnauts.com","(555) 555-5555","work","Yes","Home","email,phone,letter","A, 4","S","AK","","B, 5","C","AR","Work","City","AZ","","Fri Sep 11 2020","TBD","TBD","M","P","friend","","TBD","mp@example.com","(111) 111-1111","M","C","DC","","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","TBD","vision,hearing"
```

simply import it into google spreadsheets.

**Comment by kathyccheng** [comment]
@pbn4 here are some things I found in QA 

* Primary Applicant Phone should show [number], not [Yes, No]. It currently says Yes.
* Missing Primary Applicant Mailing Address Zip. Have street address, city and state, just missing zip.  
* Requested Accessibility is the same as Requested ADA, let’s remove Requested ADA column and keep data + header for Requested Accessibility

**Comment by kathyccheng** [comment]
@slowbot sounds good about separating concerns for basic vs custom. @pbn4 we (me or Jesse) can handle the custom export pieces, but for the raw CSV, these are the updates -- 

Basic Export

* It's the Primary Additional Phone Number that should show number. We can hide the Additional Phone Number Yes/No columns
* The Primary Applicant Resident Zip and Primary Applicant Work Zip is there, but we're missing the Primary Application Mailing Zip in the current CSV
* I agree with @kathyccheng Requested Accessibility is the same as Requested ADA Unit, let’s remove Requested ADA Unit column and keep data + header for Requested Accessibility
* Missing Requested Unit Type column
* Missing Annual and/or Monthly Income columns (can output a Income column and Monthly or Annual column for MVP)
* Add Application Timestamp Column Hour Minute Second. 05:35:20 PM

**Comment by pbn4** [comment]
@slowbot 

> Calculate and create column for Total Household Size

Isn't it the same as household size we already have?

`Prefer Two Columns for Income Monthly Income and Annual Income and only fill the value provided. I'd also like us to calculate the Annual for everyone but know that's more complicated`

What do you mean by "for everyone", because I don't see income data in household members forms.

**Comment by kathyccheng** [comment]
@pbn4 I think updates for me are: 

* Sorry if this was confusing in the last round, but we should have a column for Primary Applicant Additional Phone, and it should show the additional phone number. I think before it was showing Yes/No instead of the actual number 
* Household size should show the size of the household, if it's complex to calculate that to show there, then we can handle that manually in the spreadsheet too. For your first row for example, there is the applicant and then 2 additional household members added so I'd expect the household size to be 3. 
* Let's keep the annual and monthly income columns for now. We can do the calculations manually in the spreadsheet. So no changes needed there.

**Comment by kathyccheng** [comment]
Looks good!

**Review by bk3c — CHANGES_REQUESTED** [review]
Overall this seems like a good approach, and things generally work smoothly for me locally. A few things that I think we should address before we merge:

1. When doing local testing, I realized that application.createdAt (and .updatedAt) were getting stored and then exported in EST. I just filed #678 to look at the bigger issue, but in the meantime I think we should probably add a timezone query param to the endpoint so that we have a way to specify that. I'm ok if the functionality is just stubbed out in the short-term until #678 is worked out, though.

2. I think we should avoid converting from monthly to annual income and vice/versa, since we don't know that what value the applicant put is evenly distributed across the year, and I wouldn't want that assumption to be introduced by the system. @slowbot - am I misremembering that we had some part of this discussion already? I forget the details of where we landed.

3. Can we add a few basic tests for this, including some string values with weird characters to make sure the resulting CSV can be loaded into Excel/Numbers/Sheets even with things like quotes that potentially need to be escaped?

4. Having the 8 household members being hard-coded is creating what I think is a cumbersome number of empty columns. I'll defer to @kathyccheng and @slowbot here, but can we just set that array size to be whatever the max household size for the exported data set actually is? I realize this came up once already, but now that I'm seeing the output with 8x in Numbers, it's quite a lot.

There are also lots of other things that I think we could do to build on / maybe refactor (e.g. would we benefit from a CSV library?) some of this, but it's a great start, so we can do some or all of that later.

**Comment by bk3c** [comment]
One other technical thing: I don't think the "Requested Unit Type" field is all that useful as-is, because it's a comma-separated list that you can't sort by without parsing it (e.g. with a formula). @slowbot - can/should we de-normalize this and show the options as separate columns to enable that sorting/filtering of the resulting spreadsheet?

**Comment by bk3c** [comment]
My one other review comment is more for @slowbot than @pbn4, which is that many of the column names seem long, which makes the resulting spreadsheet pretty awkward. I guess it's easy enough to change later, but could we consider using abbreviations or whatever to make it a little more digestible?

**Comment by kathyccheng** [comment]
@slowbot @bk3c I thought the applicant can choose to indicate their income monthly or annual. For the raw CSV, shouldn't we keep what they entered? So keep both columns, and if they entered monthly fill that one, and if they entered annual fill that one but keep monthly blank? And then on the customized spreadsheet, we can do whatever additional calcs we or they want?

**Comment by kathyccheng** [comment]
@pbn4 can we add a column for Alternate Contact Agency? I just recreated the sample CSV Jesse had shared with the developers with some live data @bk3c pulled for me and I think that's the only data that we're currently missing. 

And then after having done that, here are my thoughts on some threads above. @pbn4 let's prioritize: 
1. From @bk3c:  When doing local testing, I realized that application.createdAt (and .updatedAt) were getting stored and then exported in EST. I just filed #678 to look at the bigger issue, but in the meantime I think we should probably add a timezone query param to the endpoint so that we have a way to specify that. I'm ok if the functionality is just stubbed out in the short-term until #678 is worked out, though.
2. From @bk3c: I think we should avoid converting from monthly to annual income and vice/versa, since we don't know that what value the applicant put is evenly distributed across the year, and I wouldn't want that assumption to be introduced by the system. I think we landed on let's just keep what they inputted, no need to do the calculation
3. From @bk3c: Can we add a few basic tests for this, including some string values with weird characters to make sure the resulting CSV can be loaded into Excel/Numbers/Sheets even with things like quotes that potentially need to be escaped?

@bk3c @slowbot I don't think we need to change the Requested Unit Type comma separated situation, that's honestly easy enough to do in Google Sheets if it came down to it. I also think it's fine to keep the 8 household members, I'm doing some reformatting to get to Jesse's cleaner and prettier Applications list in Google Sheets anyways so I think it's fine for the CSV tab.

**Comment by pbn4** [comment]
@kathyccheng  i don't see alternate contact agency in the applications form data. Where should I take it from? 

> From @bk3c: When doing local testing, I realized that application.createdAt (and .updatedAt) were getting stored and then exported in EST. I just filed #678 to look at the bigger issue, but in the meantime I think we should probably add a timezone query param to the endpoint so that we have a way to specify that. I'm ok if the functionality is just stubbed out in the short-term until #678 is worked out, though.

Exported CSVs use `America/Los_Angeles` timezone, where are they exported using EST?

> From @bk3c: I think we should avoid converting from monthly to annual income and vice/versa, since we don't know that what value the applicant put is evenly distributed across the year, and I wouldn't want that assumption to be introduced by the system. I think we landed on let's just keep what they inputted, no need to do the calculation

Applied.

> From @bk3c: Can we add a few basic tests for this, including some string values with weird characters to make sure the resulting CSV can be loaded into Excel/Numbers/Sheets even with things like quotes that potentially need to be escaped?

All columns are escaped according to the discussion here https://stackoverflow.com/a/4618007/2429333, commas and quotes won't break anything.

**Comment by kathyccheng** [comment]
@pbn4 if it's if they select Case Manager or Housing Counselor as their alternative contact type, the next screen has an option to indicate the Agency  

image

image

**Comment by pbn4** [comment]
@kathyccheng I added the agency column and normalized number of household members data columns based on actual household member array.

**Comment by pbn4** [comment]
@bk3c I added tests and detected some bugs. All are fixed and now I think I'm good to re-review.

**Review by bk3c — APPROVED** [review]
Tested locally, and I think this is in good shape to merge now. We can pick up all of the potential improvements in other issues as needed.

**Pull request merged**
