### PR TITLE
Update env templates

### PR DESCRIPTION
**Pull request by pbn4**
# Pull Request Template

## Issue

Addresses # (https://github.com/bloom-housing/bloom/issues/1212)
- [ ] This change addresses the issue in full
- [x] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This a cleanup of environment variable template files, mostly because they were enlisting variables that were not in use anymore. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a SQL Script

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers

### CODE REVIEW

**Comment by pbn4** [comment]
@dominikx96 Could you verify that env variables that I removed are in fact not used in partners portal (mapbox key, gtm_tag, county_code)?
@dominikx96  Also what is the LISTING_QUERY used for in partners?

**Comment by seanmalbert** [comment]
> @dominikx96 Could you verify that env variables that I removed are in fact not used in partners portal (mapbox key, gtm_tag, county_code)?
> @dominikx96 Also what is the LISTING_QUERY used for in partners?

@pbn4 ,

It doesn't appear that partners is using those keys. With listings management though, the mapbox key will probably be required, but we can add it back in when it actually is.

LISTING_QUERY is used in the next config to construct the listingServiceUrl along with BACKEND_API_BASE (`BACKEND_API_BASE + LISTINGS_QUERY`), which is partners is used in the useListings hooks.

**Comment by dominikx96** [comment]
@pbn4 I also removed unused environment variables from the NextJS config and merged the current master, LGTM 👍

**Review by dominikx96 — APPROVED** [review]

**Comment by pbn4** [comment]
@seanmalbert  Just to capture why it is not merged: waiting for next update (cc: @dominikx96 )

**Pull request merged**
