### PR TITLE
fix: restore toasts in a way which prevents infinite rerenders

### PR DESCRIPTION
**Pull request by jaredcwhite**
This PR addresses #4181

- [x] Addresses the issue in full
- [ ] Addresses only certain aspects of the issue

## Description

~~The Next.js `router.push` method can return a promise which is resolved when the new route has loaded. Instead of swallowing that (as `void`), we can provide a callback and use that for adding the toast to the toast stack. That resolves the infinite rendering issue. (I'm not quite sure why we haven't needed this solution _everywhere_, but at least now we know about it).~~

Turns out there _was_ a very specific bug which that callback fix worked around but it didn't really address it. I've since updated this PR. Here's what was going on:

Apparently, functions pulled out of React Contexts aren't stable (aka `addToast`), meaning even if you put them in the dependency array of a `useEffect` hook, it won't prevent that hook to re-execute. The fix was to write a custom hook that wraps the context in a stable ref. That way, you can put the ref itself in the dependency array, then pull `addToast` out of the ref's current value within `useEffect` for use, thus preventing unnecessary re-execution (aka infinite rerenders).

So that's good, but now there's two different methods within the codebase of accessing `addToast`—the original way which is normally fine, and the new way just for `useEffect`. I'm not thrilled about that, but I also don't want to mandate having to use the ref everywhere now which is a bit more cumbersome. Happy to entertain feedback about that in either direction.

## How Can This Be Tested/Reviewed?

Try applying to a listing which the backend has just switched off applications, or the due date is past, etc. You should see a single toast notification that the listing is now closed.

## Author Checklist:

- [ ] Added QA notes to the issue with applicable URLs
- [x] Reviewed in a desktop view
- [ ] Reviewed in a mobile view
- [ ] Reviewed considering accessibility
- [ ] Added tests covering the changes
- [ ] Made corresponding changes to the documentation
- [ ] Ran `yarn generate:client` and/or created a migration when required

## Review Process:

- Read and understand the issue
- Ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review after the updates

### CODE REVIEW

**Comment by emilyjablonski** [comment]
Screenshot 2024-09-04 at 6 52 50 PM
We'll need this fix in more places, potentially everywhere we are wanting to show a toast on a different page than where we start. For example, the RequireLogin component, which kicks in when you try and visit `account/dashboard` on the public site when you're logged out.

**Comment by jaredcwhite** [comment]
@emilyjablonski Oof…this might require a whole lot of refactoring in various places. I'm starting to wonder if there's an alternative solution, like maybe I can add a de-dup check inside of `addToast` somehow.

**Comment by emilyjablonski** [comment]
@jaredcwhite Is this ready for re-review?

**Comment by jaredcwhite** [comment]
@emilyjablonski It is now…I had to make a change based on how I actually determined was the root cause of the rerenders. See my updated PR description for the explanation: https://github.com/bloom-housing/bloom/pull/4302#issue-2506373944

**Review by emilyjablonski — APPROVED** [review]
This looks great! I would be in favor of using this new version everywhere since it works in both cases and so we don't have to remember which is which, but I don't think we necessarily need to do that conversion here.

**Review by ColinBuyck — COMMENTED** [review]
I tried hitting http://localhost:3000/applications/start/choose-language?listingId={insert-closed-listing-id} and got two toasts. Specifically, using Valley Heights Senior Community after a reseed. Are you seeing this behavior as well?

Screenshot 2024-09-18 at 10 38 58 AM

**Comment by jaredcwhite** [comment]
@ColinBuyck Hey, I tried to replicate this and I couldn't…I'm just seeing the single toast. Any other tips you could provide to trigger this?

**Comment by ColinBuyck** [comment]
@jaredcwhite sorry for not following up to this sooner! I was just retesting and was able to reproduce but found a case where only one shows. 

When I tried to hit that url with the listing id of a closed listing **without** the common app enabled, only one showed. For example, Valley Heights Senior Community after reseeding

But using the listing id of a closed listing **with** the common app enabled, two shows. For example, I reseeded, closed Blue Sky Apartments, and used that listing id within the link above and saw two toasts. Let me know if that helps you repro!

**Comment by jaredcwhite** [comment]
@ColinBuyck wow, so strange. Thanks for the info, I will investigate further!

**Comment by jaredcwhite** [comment]
@ColinBuyck Alas…I still can't repo. I tried a few times and in a couple different browsers. Could be a dev/env specific issue of some sort?

I might recommend we do a test in a staging environment post-merge, unless you can trigger this in the deploy preview?

**Comment by ColinBuyck** [comment]
@jaredcwhite Hmm I also can't seem to repro on the deploy preview. I wonder if there's some sort of race condition going on but I am okay with merging and keeping an eye on it! Thanks for the discussion on this ⏱️

**Review by ColinBuyck — APPROVED** [review]
LGTM 🥼

**Pull request merged**
