### PR TITLE
2335/fixes adding user that's already created

### PR DESCRIPTION
**Pull request by YazeedLoonat**
## Issue Overview

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/2335)

- [x] This change addresses the issue in full

## Description
This fixes an error where if an email was already tied to a public user, then trying to add them as a partner was causing an error

## How Can This Be Tested/Reviewed?
Go into public site and add a new user 
go into the partner site and attempt to add that exact same user as a partner (there is currently discussion going on around if admin users should show in the user table)
the user should now be added correctly 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [x] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by seanmalbert — CHANGES_REQUESTED** [review]
@YazeedLoonat ,

I think we need a little more work to get this working as expected. You updated `_createUser` and it returns the user to `invitePartnersPortalUser`, and then the invite flow continues. We probably want them to still receive the confirmation, but since `_createUser` is now returning before the confirmation token can be generated, the confirmation link in the email isn't valid.

Another problem is that `_createUser` is also used by `createPublicUser` and in that case we still want `_createUser` to return the email in use error, so we either need to add an argument to `_createUser` to add some logic or split some things out so they're not used by both functions.

**Comment by YazeedLoonat** [comment]
Hey @seanmalbert I got the issues you pointed out addressed, lemme know what you think

**Comment by emilyjablonski** [comment]
@YazeedLoonat Heads up on some failing backend tests to resolve

**Review by emilyjablonski — CHANGES_REQUESTED** [review]
If I create a user in public I can log-in as that user to partners even though they don't have access, though it doesn't show me any listings. The same occurs if I create a user in partners, I can log-in to public without having created a public account (it seems to default the birthday).

**Comment by seanmalbert** [comment]
> If I create a user in public I can log-in as that user to partners even though they don't have access, though it doesn't show me any listings. The same occurs if I create a user in partners, I can log-in to public without having created a public account (it seems to default the birthday).

@YazeedLoonat ,

There is an existing [issue](https://github.com/bloom-housing/bloom/issues/1873) to cover the case where a public user can login to the partner portal, but cannot access anything. I think it's acceptable that a partner user can login to the public site as long as we fix #2403. I moved both issues into next sprint.

**Review by seanmalbert — CHANGES_REQUESTED** [review]
@YazeedLoonat ,

This may have been a problem with how you had it before, so I apologize for not calling this out earlier if that's the case, but this does not correctly handle a public account getting created with the same email address multiple times. It doesn't create duplicates, but starts the confirmation process over again for the user.

Rather than try and get `_createUser` working for both public and partner portal cases, I think we should have two separate functions. Looking at the user service as a whole now, it could use a refactor to split out into two services, but that can be for another issue.

Please make sure you create tests for the new function(s).

**Comment by YazeedLoonat** [comment]
This should be good for re-review now

**Comment by emilyjablonski** [comment]
Issue AC LGTM, I could have lost some of the desired behavior but currently I if I already have a partners account I cannot create a public account with that e-mail, is that expected?

**Comment by seanmalbert** [comment]
> Issue AC LGTM, I could have lost some of the desired behavior but currently if I already have a partners account I cannot create a public account with that e-mail, is that expected?

Yes, since there are no roles associated with a public account, all partner portal users have the ability to login to the public site.

**Review by seanmalbert — APPROVED** [review]

**Pull request merged**
