### PR TITLE
fix: only show lottery button if app has results

### PR DESCRIPTION
**Pull request by emilyjablonski**
This PR addresses #4303

- [x] Addresses the issue in full
- [ ] Addresses only certain aspects of the issue

## Description

Only show `View lottery results` button if we actually have results - which will by default filter out duplicates that don't have results if they were not included in the lottery.

## How Can This Be Tested/Reviewed?

Ensure the button only shows on a published lottery listing if the application has results (which it won't for a duplicate you confirm and exclude from the lottery).

## Author Checklist:

- [x] Added QA notes to the issue with applicable URLs
- [x] Reviewed in a desktop view
- [x] Reviewed in a mobile view
- [x] Reviewed considering accessibility
- [ ] Added tests covering the changes
- [ ] Made corresponding changes to the documentation
- [ ] Ran `yarn generate:client` and/or created a migration when required

## Review Process:

- Read and understand the issue
- Ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review after the updates

### CODE REVIEW

**Review by ludtkemorgan — COMMENTED** [review]
Is this the intended behavior to show a different status for the application if it was marked as duplicate? It shows `applications closed` instead of `lottery run`
image

**Comment by emilyjablonski** [comment]
@ludtkemorgan Chatted w Sarah and updated it so they now both say lottery run!
Screenshot 2024-09-25 at 2 47 29 PM

**Review by ColinBuyck — APPROVED** [review]
LGTM 🪀 Assuming that test fix goes through

**Review by ludtkemorgan — APPROVED** [review]
🦒

**Pull request merged**
