### PR TITLE
fix: prevent public users from logging into partners

### PR DESCRIPTION
**Pull request by ludtkemorgan**
# Pull Request Template

## Issue Overview

This PR addresses #3226

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

There is currently an issue in production where a user can create an account in the public site then go to the partner site and successfully login. They are not able to see any data, but it is not best practice to allow this.

This PR blocks the actual login of the public users by seeing if the login origin url is the partner url and comparing it to the partners url setup in the environment variable

## How Can This Be Tested/Reviewed?

1. Reseed the backend
2. Create an account on the public site
3. Logout and go to the partner site
4. Try to log in on the partner site
5. You should get an error message

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by emilyjablonski** [comment]
@ludtkemorgan Wondering if the experience I'm seeing locally is just going to happen locally - but if I login to public and I open partners I am automatically logged into partners already

**Comment by ludtkemorgan** [comment]
> @ludtkemorgan Wondering if the experience I'm seeing locally is just going to happen locally - but if I login to public and I open partners I am automatically logged into partners already

@emilyjablonski I think that might just be a local issue. I'm not able to replicate it in the exygy dev site.

**Review by ColinBuyck — COMMENTED** [review]
I'm noticing that the password attempts count is not decreasing with an email associated with a public account. Also, when trying to log in first with a partner's account + incorrect password the count will decrease but once you attempt to log in with a existing partner's account, it resets to 5.
Screenshot 2023-07-21 at 3 47 50 PM

**Comment by YazeedLoonat** [comment]
> @ludtkemorgan Wondering if the experience I'm seeing locally is just going to happen locally - but if I login to public and I open partners I am automatically logged into partners already

Hey @emilyjablonski this has to do with the cookies change over. Since locally public and partners is on the same site (localhost) they will share cookies. The hosted sites are all on their own site so they won't share cookies

hopefully that helps clear up why that's happening for ya

**Comment by YazeedLoonat** [comment]
@ludtkemorgan @ColinBuyck I'm not sure if we want to count down for a public user trying to get into the public site. That count also locks someone out of being able to log into the public site, do we want to lock people out of the public site if they attempted to log into the partner site?

**Comment by ColinBuyck** [comment]
@YazeedLoonat @ludtkemorgan I definitely see your point! I was considering the security side since the countdown could then indicate which users have an account. In reviewing now though, I'm realizing that this is an existing behavior that both public emails and emails not tied to an account will not cause a countdown. Exposing the info we had removed from the forgot password flow. So I'm thinking what I'm describing should just be a separate ticket if you all agree?

**Comment by YazeedLoonat** [comment]
@ColinBuyck I agree! I'm going to give this a `LGTM`

**Review by YazeedLoonat — APPROVED** [review]
LGTM

**Comment by ludtkemorgan** [comment]
@ColinBuyck I think that should be a separate ticket. We shouldn't count down a public user attempting to get into partners. Deciding what to do with a public user attempting to get into the public site is a separate issue

**Comment by ColinBuyck** [comment]
> We shouldn't count down a public user attempting to get into partners

@ludtkemorgan I agree with this with the current behavior (lock out on partner's equals a lockout on public) but I think in an ideal world, I'd prefer for our count down approach to be more nuanced to avoid exposing user emails and the types of accounts they're associated with.

**Review by ColinBuyck — APPROVED** [review]
LGTM 🔑

**Pull request merged**
