### PR TITLE
Add household members

### LINKED ISSUE #262: Application: Add Household Members and Contact Details
**Goal:** As an applicant I want to provide details about my household in order to determine my eligibility for a housing opportunity.

**Acceptance Criteria:**
- Applicant should be prompted to provide additional household members
   -  Options include:
      - Add Household Member
      - Done Adding People
   - As household members are added each name is listed alongside their relationship to the primary applicant. Each applicant listed is editable from this screen.
- After selecting the Add Household Member option, the applicant is prompted to provide contact information for the individual household member
   - Applicant is prompted to provide the name of the household member. Fields include:
      - First Name
        - If no value is entered a presence validation reads: Please enter a First Name
      - Middle Name
      - Last Name
        - If no value is entered a presence validation reads: Please enter a Last Name
   - Applicant is prompted to provide the date of birth of the household member.
      - If no DOB is entered a presence validation reads: Please enter a valid Date of Birth
   - Applicant is prompted to clarify if the household member has the same address as the primary applicant
      - If no, applicant is prompted to provide the current living address for the household member
      - If no option is selected a presence validation reads: Please select one of the options above.
   - Applicant is prompted to clarify whether the household member works in the jurisdiction
      - If no option is selected a presence validation reads: Please select one of the options above.
   - Applicant is prompted for the relationship to the household member. Options include:
      - Spouse
      - Registered Domestic Partner
      - Parent
      - Child
      - Sibling
      - Cousin
      - Aunt
      - Uncle
      - Nephew
      - Niece
      - Grandparent
      - Great Grandparent
      - In Law
      - Friend
      - Other
      - If no option is selected a presence validation reads: Please select your relationship to the household member
   - Options at the bottom of the Household Member Contact page include:
      - Save Household Member
      - Cancel Adding this Person

image

image

### PR DESCRIPTION
**Pull request by software-project**
Fixes #262 

Couple questions here:
UI:
- @slowbot should primary applicant be editable same way household members now? For now I've made it to link to earlier pages of the application
- Should `cancel adding household members` delete the member? It feels weird to do so when someone comes back to edit member and deletes him/ her.
Technical:
@bk3c  @jaredcwhite I've made some structural changes to the application. Main one being unifying household members and applicant into a separate interface. Please have a look there if it looks fine.

### CODE REVIEW

**Comment by jaredcwhite** [comment]
@software-project Moving applicant details into embedded objects makes sense to me. I noticed there's a lot of duplication though in the blankApplication data structure now…were you planning to remove the fields we don't need now that we have the applicant object?

**Comment by software-project** [comment]
@slowbot regarding point 1. I think we should be able to link top nav to go back to household. But I think it should be within scope of this task as top nav is not working here. I fixed points 2 and 3 and also addressed cleanup that @jaredcwhite asked for. I didn't delete them earlier as I wasn't sure if thats the way we want to go.

**Comment by software-project** [comment]
Another round of changes. It's rebased off master with @pbn4 changes for alternate contact and state select.

**Comment by software-project** [comment]
@slowbot should be fixed now

**Comment by software-project** [comment]
@bk3c or @jaredcwhite can you have a look so we ca merge this one. Jest test that are failing are from master I believe

**Pull request merged**
