### PR TITLE
Add support for second button to <Hero />

### PR DESCRIPTION
**Pull request by james-wills-sf**
Jira ticket: [[DAH-746](https://sfgovdt.jira.com/browse/DAH-746)]

Our homepage Hero component needs to have two links, one for rental, and one for sale listings. This change just adds support for a second button on the `<Hero />` component without breaking backwards compatibility.

## Screenshot: `<Hero />` w/ two buttons
- 2021-05-07 at 3 27 01 PM

### CODE REVIEW

**Comment by james-wills-sf** [comment]
Hey @emilyjablonski !

Here's a small update to the `<Hero />` component to add support for two buttons, do you mind reviewing it?

**Review by emilyjablonski — APPROVED** [review]
Looks great! :)

**Comment by james-wills-sf** [comment]
Thanks for the review, @emilyjablonski, how do you want to do the merge?

I was thinking we would squash merge and update the commit message there, but I'm not sure what bloom's commit message best practices are. Let me know!

**Comment by emilyjablonski** [comment]
Feel free to squash and merge! I don't believe we are enforcing any commit message format at the moment :)

**Comment by seanmalbert** [comment]
@emilyjablonski , @james-wills-sf , it looks like you're both good to have this merged. One question first though, can you foresee having to add any more buttons to the hero image? If so, would it be better to now update the Hero component to accept buttons as an array `buttons: { title: string, link: string }[]` and then map their output? If not or it's reasonable to wait until a third is required, then let's get this merged in today.

**Pull request merged**
