### PR TITLE
feat: add address holder fields to paper application

### PR DESCRIPTION
**Pull request by KrissDrawing**
# Pull Request Template

## Issue Overview

This PR addresses #3705 #3693

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Adds address holder name and relationship fields to paper application. Also even thought address was required to submit if present, it wasn't highlighting errors, so i fixed that. 

This PR was affecting also Application summary, so to avoid wrong labels i connected it with #3693.

## How Can This Be Tested/Reviewed?

On partners go to listing -> applications tab. If db freshly seeded editing/adding application should work as before. Changing settings -> preferences -> options to collect address and then selecting yes on address holder name and/or relationship will show the fields in paper application when preference option checked. Also select "verify address by radius", and pick radius value, so you can test all 3 validation variants. 

1. In paper application you should now be able to add name and relationship to preference option (and then it should be visible in summary)
2. To see address verification field in summary you need to fill digital application.

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by emilyjablonski — CHANGES_REQUESTED** [review]
A few notes!
* We recently removed placeholder text from all input fields in the application, so we'll need to remove the placeholder text from the fields in the address verification section. In addition we've moved from `City Name` to `City` and `Zipcode` to `Zip Code` - you can check out the mock for these if that's helpful.
* If I edit an existing paper application and add a name/address on a preference and hit save, then re-edit the application, the data isn't there.
* On the saved view of a paper application, (1) I would expect to see the `Address` header larger and bolder as other address headers are in the application, but I didn't see a mock for this screen so no worries if current behavior is expected! Also in this view, (2) I was surprised to see the name of the address holder come after the address, when in the edit view it comes before. Lastly, (3) the first street input is getting pretty squished, but again not sure if there is a mock here or not.
Screenshot 2023-12-04 at 4 13 59 PM

**Comment by KrissDrawing** [comment]
@emilyjablonski  fixed everything aside of unknown design changes.

1. for address being bolder it might be confusing as it will be significantly bigger than preference / option name.
2. for the address summary i guess i can add a prop to change it to have same structure as [this form](https://www.figma.com/file/Ne8jOyPpCBvlAhyaRlXgTq/Geocoding?type=design&node-id=1387-16396&mode=design&t=Tn2VQ0yS47hbu99n-0).

@slowbot can you check if that summary view looks good

image

**Comment by ludtkemorgan** [comment]
@KrissDrawing have you had a chance to look at this?

**Comment by KrissDrawing** [comment]
@ludtkemorgan I am waiting for approval of the design or suggestions regarding the things Emily pointed out. For the aspects I was unsure about, I have left notes in my previous comment.

@slowbot can you check screenshot from my comment above?
I need to know if I should:
1. Change the structure of the summary address so that it resembles the one used in the form.
2. Increase the size of the `Address` "header".

**Review by emilyjablonski — APPROVED** [review]

**Pull request merged**
