### PR TITLE
Add info card grid

### PR DESCRIPTION
**Pull request by software-project**
Adds InfoCardGrid for #305

### CODE REVIEW

**Comment by bk3c** [comment]
@software-project Now that we're using Lerna, you don't need to increment version numbers in any of your PRs, we do it as part of the publishing process and doing it sooner just breaks CI since the new versions aren't published to NPM yet. Otherwise LGTM.

**Comment by software-project** [comment]
@bk3c uhhh, I was trigger happy on using `yarn new-release` then, will delete version update.

**Comment by software-project** [comment]
@slowbot next step would be merging it to `translation-nav` or merging translation-nav first and then this to master. After that I can push the changes upstream and update the components there.

**Comment by bk3c** [comment]
@software-project I actually wan't aware of `yarn new-release`, so thanks for teaching me something new today (and reverting the commit in addition). 

I think #307 is waiting on @jaredcwhite's review, so I'm good with any merge sequence that makes sense to the two of you, including merging this there or merging that to master when it's ready and then this afterward.

So LGTM and ready to merge as desired.

**Pull request merged**
