### PR TITLE
feat: Updates application confirmation numbers

### PR DESCRIPTION
**Pull request by dominikx96**
# Pull Request Template

## Issue Overview

This PR addresses #1918

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Updates confirmation numbers in the public and partners app views. To keep backward compatibility, an old number (longer) shows for old applications.

## How Can This Be Tested/Reviewed?
Create a new application, you should see 8-sign code as a confirmation in:

public:
- account: applications list
- confirmation screen
- confirmation email
- csv export

partners:
- Applications list
- Application detail (header and the first section)
- Application edit (header)
- Flags

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by kathyccheng** [comment]
The CSV export piece will be handled in a separate issue, https://github.com/bloom-housing/bloom/issues/2092
Sorry should've updated the issue

**Comment by emilyjablonski** [comment]
> Do you have suggestions for how I can test that legacy applications are using the old number? The new number looks great everywhere but CSV.

@dominikx96

**Comment by seanmalbert** [comment]
@dominikx96 , I added the confirmation number to the csv export.

**Review by seanmalbert — APPROVED** [review]

**Comment by seanmalbert** [comment]
@emilyjablonski ,
There isn't a good way to test with legacy applications using the old confirmation code (application id), because there was a migration script created the migration codes for applications that don't have it. So even in production now, all applications have the new confirmation code.

**Review by emilyjablonski — APPROVED** [review]

**Pull request merged**
