### PR TITLE
feat: show dismissable alert when updating afs

### PR DESCRIPTION
**Pull request by emilyjablonski**
# Pull Request Template

## Issue Overview

This PR addresses #2860 

- [x] This change addresses the issue in full

## Description

When you update an application flagged set to resolved, an alert should pop up indicating how many applications you have verified. It should persist between all users until it is explicitly dismissed, even after logging out.

## How Can This Be Tested/Reviewed?

Resolve an application flagged set and ensure the alert appears. Ensure it persists on the resolved set page until it is dismissed.

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by ColinBuyck — COMMENTED** [review]
@emilyjablonski Everything looks good, just have one design comment. It seems that the alert is shifting both the table and the save button down in the PR, but it only shifts the table down in the Figma.
PR: 
Screen Shot 2022-09-23 at 9 46 21 AM

Figma:
Screen Shot 2022-09-23 at 9 46 12 AM

**Review by ludtkemorgan — APPROVED** [review]
This looks good assume you address Colin's finding

**Comment by emilyjablonski** [comment]
@ColinBuyck Fixed, thank you!

**Review by ColinBuyck — APPROVED** [review]
🍾

**Pull request merged**
