### PR TITLE
fix: partners highlight field on backend error

### PR DESCRIPTION
**Pull request by ludtkemorgan**
# Pull Request Template

## Issue Overview

This PR addresses #3430, #3232

- [ ] This change addresses the issue in full
- [x] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

There are two issues happening on the Listing edit/add form in partners. Both are due to components re-rendering when they shouldn't need to.

1st issue: When clicking save the errors are not highlighting the fields that need resolution. This is happening because there is an additional re-render that is triggering the useEffects in Units.tsx and CommunityType.tsx, LeasingAgent.tsx. Both of which are resetting the values in the form,
- Fix # 1: Change Reset in Units.tsx to a setValue when the value is undefined or null. One has to be selected so this works in all cases.
- Fix #2: Change reset in CommunityType.tsx to a setValue. This one works, but if an error happens on submission it will reset it back to the original value if you change it to the unset value
- Fix #3: Change the clearErrors to only run if the value has changed (the user has typed or deleted something in the field)

2nd issue: When typing in most fields every character typed/deleted causes a re-render of all the form components. You can easily notice this if you have a photo already added and start typing characters in another field (e.g "Listing name"). The photo component can easily be spotted as being re-rendered
- Fix: change the "onChange" commands to only clear the error if there is actually an error
- My solution works a majority of the time, but it still sometimes causes additional re-renders

These are both things we should add or investigate further as the case in the 1st option. However, we should investigate what changed recently to cause all of these additional re-renders. 

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by ludtkemorgan** [comment]
@ColinBuyck The bug you mentioned in standup https://github.com/bloom-housing/bloom/issues/3232 was a similar issue so I fixed it I think with my most recent commit.

This is ready to review. As far as I know there is still one bug but it can be reviewed and QA'd for everything else.

Bug:
1. Edit a listing that has a community type
2. Change the following things:
  - Change the community type to a different type
  - Make a change in one of the other fields that will cause an error (e.g. delete the name field)
3. Click save and the community type will be reset back to the original type

**Review by ColinBuyck — COMMENTED** [review]
Just a few nits 🪰 
The error on the Jursidiction field doesn't seem to clear after selecting a jurisdiction
Screenshot 2023-05-16 at 3 24 29 PM

The leasing agent phone number doesn't highlight red despite being a required field
Screenshot 2023-05-16 at 3 26 34 PM

**Review by YazeedLoonat — APPROVED** [review]
once colin's comments are addressed I think this is good to go!

**Review by ColinBuyck — APPROVED** [review]
Gave it another pass and this LGTM once the two pieces above are addressed 🧊

**Comment by ludtkemorgan** [comment]
@YazeedLoonat @ColinBuyck Thanks for reviewing! I fixed the leasing agent phone number and jurisdiction issues identified.

**Pull request merged**
