### PR TITLE
fix: use translated labels on the progress bar when at the choose lan…

### PR DESCRIPTION
**Pull request by lisunshiny**
…guage step

# Pull Request Template

## Issue Overview

This PR addresses a minor translation bug on the ProgressNav that was found while diving into #3221.

- [ ] This change addresses the issue in full
- [x] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Other instances of ProgressNav use the conductor to populate labels. this is the only one that got missed. [Example](https://github.com/bloom-housing/bloom/blob/dbe90d5d8749369b3757a9c78a155b306fa4b1a9/sites/public/src/pages/applications/household/members-info.tsx#L58).

## How Can This Be Tested/Reviewed?

Change language to non-English. Start an application on `main`, note that the first screen (choose language) has a progress nav in English

Change language to non-English. Start an application on this branch, note that the first screen (choose language) has a properly translated progress nav. You can also click to different languages and the progress nav will properly change as well.

image

image

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by ColinBuyck — APPROVED** [review]
LGTM 🥧

**Review by ludtkemorgan — APPROVED** [review]
Thanks for making this change. Looks good to me. I've given you write ability, so you should be able to merge this PR. Make sure you select "squash"

**Comment by lisunshiny** [comment]
Thanks! Squash merge is the best merge ✌🏼

hmm it's still saying I don't have access (and I checked my email and didn't get any invites), could you take a second look? ty

Screenshot 2023-02-01 at 3 30 08 PM

**Comment by ludtkemorgan** [comment]
> Thanks! Squash merge is the best merge ✌🏼
> 
> hmm it's still saying I don't have access (and I checked my email and didn't get any invites), could you take a second look? ty
> 

Weird, it shows that you have write access. Could you try to log out and in of github? I wonder if it just didn't pick up the change

**Comment by ludtkemorgan** [comment]
Oh yeah, I think that is the case. I'll merge it and let the team know that going forward we might need to merge your PRs

**Pull request merged**
