### PR TITLE
fix: community type disclaimer frontend

### PR DESCRIPTION
**Pull request by KrissDrawing**
This PR addresses #4476 #4477 

- [x] Addresses the issue in full
- [ ] Addresses only certain aspects of the issue

## Description

Adds optional disclaimer to application. Both partners and public site.

## How Can This Be Tested/Reviewed?

In partners site in reserved community type there is new section that allows to specify if that section should appear. If it's yes it should require both fields (title and disclaimer). Make sure it works fine for editing, adding new listing, when other fields throwing an error etc. (as there was issues with that in meantime).
when "yes" and both fields filled it should appear as first step of application (right after language select). Make sure it works also without it, and form works properly (like navigation back etc)

## Author Checklist:

- [ ] Added QA notes to the issue with applicable URLs
- [x] Reviewed in a desktop view
- [x] Reviewed in a mobile view
- [x] Reviewed considering accessibility
- [x] Added tests covering the changes
- [ ] Made corresponding changes to the documentation
- [ ] Ran `yarn generate:client` and/or created a migration when required

## Review Process:

- Read and understand the issue
- Ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review after the updates

### CODE REVIEW

**Comment by ColinBuyck** [comment]
Flagging that the public build failed along with some other tests 🥽

**Review by mcgarrye — CHANGES_REQUESTED** [review]
Looks good, only thing is that you can add a disclaimer without selecting a community type and it does appear in the application flow. It also shows as required when no community type is selected.
Screenshot 2024-12-03 at 4 49 52 PM

**Comment by mcgarrye** [comment]
Great fix for no selection.
However, noticing it is not translating on the public site and that is a AC within the epic

**Review by mcgarrye — APPROVED** [review]
LGTM

**Pull request merged**
