### PR TITLE
Enhancements to the partners Signin Page

### PR DESCRIPTION
**Pull request by jaredcwhite**
Addresses #391

### CODE REVIEW

**Comment by jaredcwhite** [comment]
@slowbot This is ready to try out now. I think the error handling should be working pretty well now

**Comment by jaredcwhite** [comment]
Sounds good to me 👍￼

**Comment by jaredcwhite** [comment]
OK, ready for another review @slowbot

**Comment by jaredcwhite** [comment]
FYI—I just noticed this comment by @kathyccheng on the original issue:

> This also needs to include a deny state for if you don't have the proper permission, e.g. if you try to log in with a public user account. @slowbot can you define an error message here?

**Comment by kathyccheng** [comment]
@jaredcwhite cc @slowbot we just talked about using the same general looks like you don't have account message here. no need for a specific message per Jesse's suggestion above. Just want to know for testing purposes that public account won't be able to access the partner's portal and that part of our permissions has been hooked up properly.

**Comment by jaredcwhite** [comment]
All right, so in that case are we good to merge this in now?

**Pull request merged**
