### PR TITLE
Add env variables to control rate limits

### PR DESCRIPTION
**Pull request by bpsushi**
Add two env variables THROTTLE_TTL and THROTTLE_LIMIT to control global rate limits. Variables are not required. By default it is set to almost infinite.

This resolves the issue where Cypress tests hits rate limits.

### CODE REVIEW

**Comment by emilyjablonski** [comment]
It looks like the `terms` Cypress suite is still failing in CI on this branch, is that expected / is some other change needed?

**Comment by pbn4** [comment]
@bpsushi Why did you remove throttle for /submit, is it not globally configured? Also tests are red at the moment

**Comment by bpsushi** [comment]
> It looks like the `terms` Cypress suite is still failing in CI on this branch, is that expected / is some other change needed?

@emilyjablonski im not 100% sure, but it looks like now Cypress is failing on other error, that is not related to the rate limit. Can you please double check the reason of failing?



> @bpsushi Why did you remove throttle for /submit, is it not globally configured? 
It is now configured globally. Decorator used before is no more needed.

> Also tests are red at the moment
Yup i see. Will try to reproduce locally

**Comment by emilyjablonski** [comment]
The error you're getting now in the `terms` suite is the same error we get with the rate limiting issue, so I think it's failing for the same reason

**Comment by bpsushi** [comment]
@pbn4 lint and all test fixed, only Cypress is failing but it looks like totally unrelated issue.
I had to change CircleCi configuration a little - i have added Redis container for Cypress executor, since it is using backend app.

@emilyjablonski please take a look at cypress tests, they are failing on navigation.ts with timed out error.

**Comment by emilyjablonski** [comment]
Yup that suite is unrelated, looks great!

**Comment by emilyjablonski** [comment]
Just a heads up that the terms suite was commented out on master until this fix goes in 👍

**Pull request merged**
